#!/usr/bin/env python3
"""Phase 17.0 acceptance: TLS ALPN (RFC 7301), negotiated for real inside
QEMU against a genuine TLS 1.3 server (Python's `ssl` module, which has its
own independent ALPN implementation via OpenSSL -- not Aurora's).

httpsget's CLI has no way to target a non-443 port (the `<host>` argument
is copied verbatim into the URL's host with the port hardcoded to 443 --
see fetch_one() in user/httpsget.c), so all three scenarios below share a
SINGLE long-lived server on port 443, reconfiguring the SSLContext's own
`set_alpn_protocols()` between scenarios (this is safe: each scenario is
its own sequential QEMU boot, so there is never a connection from one
scenario still in flight when the next scenario reconfigures it) rather
than trying to run three servers on three ports:

  1. Server ALPN list = ["http/1.1"] only: `httpsget --alpn 10.0.2.2
     /page1` offers ["h2", "http/1.1"]; the intersection is exactly
     {http/1.1}, so the server selects it. Aurora should detect
     "http/1.1" (not h2) and proceed completely normally -- the real HTTP
     request that follows is confirmed server-side, then status=200.
  2. Server ALPN list = ["h2", "http/1.1"] (h2 preferred): RFC 7301 has
     the SERVER's own preference govern selection when both are mutually
     offered, so the server selects "h2". Aurora must detect this and
     refuse to continue the connection as HTTP/1.1 (Phase 17.0 is ALPN
     only, no HTTP/2 framing yet) -- verified two ways: the client's own
     log shows the refusal and never reaches status=200, AND the server
     independently confirms NO further bytes ever arrive on that
     connection after the handshake (proving Aurora really did stop, not
     just misreport success).
  3. Same server ALPN list, but `httpsget 10.0.2.2 /page3` is invoked
     WITHOUT --alpn: the server's own selected_alpn_protocol() comes back
     None, which (given the server has h2 and http/1.1 both configured)
     can only mean the ClientHello carried no ALPN extension at all --
     confirming --alpn's opt-in design, byte-identical to every pre-17.0
     ClientHello, when the flag isn't given.

Self-contained and reproducible: no private keys are committed; the
production user/ca_roots.h is restored on exit. Requires: qemu-system-i386,
openssl, the cross toolchain. Run from the repo root: python3 tools/alpn_qemu.py
"""
import os, socket, ssl, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    key, pem, der = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem"), os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora ALPN Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by alpn_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def canned(status, body, connection):
    b = body.encode()
    return (f"HTTP/1.1 {status}\r\nContent-Length: {len(b)}\r\n"
            f"Connection: {connection}\r\n\r\n").encode() + b


def start_server(port, certfile, keyfile, current_result):
    """Serves forever on `port`; the ALPN protocol list is whatever the
    shared SSLContext (returned alongside the listening socket) is
    configured with AT THE TIME a given connection's handshake happens --
    the caller reconfigures it between scenarios. Each connection's result
    (alpn, request_line if any) is written into `current_result`, which the
    caller clears before each scenario."""
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_3
    ctx.load_cert_chain(certfile=certfile, keyfile=keyfile)

    def handle(conn):
        try:
            tls = ctx.wrap_socket(conn, server_side=True)
        except (ssl.SSLError, OSError):
            conn.close(); return
        current_result["alpn"] = tls.selected_alpn_protocol()
        tls.settimeout(5)
        try:
            data = tls.recv(4096)
        except (socket.timeout, ssl.SSLError, OSError):
            data = b""
        if data:
            current_result["request_line"] = data.split(b"\r\n", 1)[0].decode(errors="replace")
            try:
                while b"\r\n\r\n" not in data:
                    more = tls.recv(4096)
                    if not more: break
                    data += more
                tls.sendall(canned("200 OK", "ok", "close"))
            except (ssl.SSLError, OSError):
                pass
        try: tls.close()
        except OSError: pass

    raw = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    raw.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    for attempt in range(20):
        try:
            raw.bind(("0.0.0.0", port)); break
        except OSError:
            if attempt == 19: raise
            time.sleep(0.2)
    raw.listen(8)

    def loop():
        while True:
            try:
                conn, _ = raw.accept()
            except OSError:
                return
            threading.Thread(target=handle, args=(conn,), daemon=True).start()

    threading.Thread(target=loop, daemon=True).start()
    return raw, ctx


def run_qemu(serial_path, typed_cmd, wait_s=25):
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash", "-": "minus"}
        def key_for(ch):
            if ch in km: return km[ch]
            if ch.isupper(): return "shift-" + ch.lower()
            return ch
        for ch in typed_cmd:
            s.sendall(("sendkey " + key_for(ch) + "\n").encode()); time.sleep(0.12)
        s.sendall(b"sendkey ret\n"); time.sleep(wait_s)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-17x0-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    fails = 0
    srv = None
    try:
        pem, key, der = gen_cert(work)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1

        current_result = {}
        srv, ctx = start_server(443, pem, key, current_result)

        # ---- scenario 1: server can only pick http/1.1 -- normal request follows ----
        ctx.set_alpn_protocols(["http/1.1"])
        current_result.clear()
        log1 = run_qemu(serial, "httpsget --alpn 10.0.2.2 /page1 %d" % int(time.time()))
        r1 = dict(current_result)

        checks = [
            ("scenario 1: server negotiated \"http/1.1\"", r1.get("alpn") == "http/1.1"),
            ("scenario 1: client log shows ALPN negotiated: http/1.1",
             "ALPN negotiated: http/1.1" in log1),
            ("scenario 1: a real HTTP request followed", r1.get("request_line", "").startswith("GET /page1")),
            ("scenario 1: status=200 reached", "status=200" in log1),
        ]

        # ---- scenario 2: server prefers h2 -- Aurora must refuse to continue ----
        ctx.set_alpn_protocols(["h2", "http/1.1"])
        current_result.clear()
        log2 = run_qemu(serial, "httpsget --alpn 10.0.2.2 /page2 %d" % int(time.time()))
        r2 = dict(current_result)

        checks += [
            ("scenario 2: server negotiated \"h2\"", r2.get("alpn") == "h2"),
            ("scenario 2: client log shows ALPN negotiated: h2", "ALPN negotiated: h2" in log2),
            ("scenario 2: client log shows the refusal to continue",
             "does not speak HTTP/2 yet" in log2 or "refusing to continue" in log2),
            ("scenario 2: status=200 was NOT reached (connection correctly abandoned)",
             "status=200" not in log2),
            ("scenario 2: server confirms NO further bytes ever arrived after the handshake",
             "request_line" not in r2),
        ]

        # ---- scenario 3: --alpn omitted -- no ALPN extension sent at all ----
        ctx.set_alpn_protocols(["h2", "http/1.1"])   # server still supports both; client offers neither
        current_result.clear()
        log3 = run_qemu(serial, "httpsget 10.0.2.2 /page3 %d" % int(time.time()))
        r3 = dict(current_result)

        checks += [
            ("scenario 3: server saw no ALPN match at all (proves none was offered)",
             r3.get("alpn") is None),
            ("scenario 3: client log has no ALPN line (flag wasn't given)",
             "ALPN" not in log3),
            ("scenario 3: a real HTTP request followed normally", r3.get("request_line", "").startswith("GET /page3")),
            ("scenario 3: status=200 reached", "status=200" in log3),
        ]

        for name, ok in checks:
            print(f"{name:75}: {'PASS' if ok else 'FAIL'}")
            if not ok: fails += 1
    finally:
        if srv:
            try: srv.close()
            except OSError: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n17.0 ALPN (QEMU, real server): " + ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
