#!/usr/bin/env python3
"""Phase 16.2 acceptance: HTTP Basic and Bearer authentication, negotiated
for real inside QEMU against genuine TLS 1.3 servers (Python's `ssl`
module).

Three scenarios, each a fresh QEMU boot:

  1. `httpsget --auth-basic alice:s3cr3t 10.0.2.2 /basic` -- the server
     inspects the REAL incoming Authorization header, decodes the base64
     ITSELF (Python's own base64 module, not trusting httpsget's encoder),
     and confirms it decodes to exactly "alice:s3cr3t".
  2. `httpsget --auth-bearer mytoken123 10.0.2.2 /bearer` -- the server
     confirms the exact header value "Bearer mytoken123".
  3. `httpsget --auth-bearer secret999 10.0.2.2 /hop` -- /hop (origin A,
     :443) redirects to a DIFFERENT origin B (:8443); B's server confirms
     NO Authorization header arrives there at all, proving credentials
     scoped to origin A don't leak to a redirect target on a different
     origin (Phase 16.2's documented, deliberately stricter-than-most-
     clients behavior).

Self-contained and reproducible: no private keys are committed; the
production user/ca_roots.h is restored on exit. Requires: qemu-system-i386,
openssl, the cross toolchain. Run from the repo root: python3 tools/auth_qemu.py
"""
import base64, os, socket, ssl, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    key, pem, der = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem"), os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora Auth Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by auth_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def canned(status, body, connection, location=None):
    b = body.encode()
    loc = f"Location: {location}\r\n" if location else ""
    return (f"HTTP/1.1 {status}\r\n{loc}Content-Length: {len(b)}\r\n"
            f"Connection: {connection}\r\n\r\n").encode() + b


def start_server(port, certfile, keyfile, on_request):
    """on_request(path, headers_dict) -> response bytes."""
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_3
    ctx.load_cert_chain(certfile=certfile, keyfile=keyfile)

    def handle(conn):
        try:
            tls = ctx.wrap_socket(conn, server_side=True)
        except (ssl.SSLError, OSError):
            conn.close(); return
        buf = b""
        try:
            while True:
                while b"\r\n\r\n" not in buf:
                    chunk = tls.recv(4096)
                    if not chunk:
                        return
                    buf += chunk
                head, _, buf = buf.partition(b"\r\n\r\n")
                lines = head.split(b"\r\n")
                path = lines[0].split(b" ")[1].decode()
                headers = {}
                for l in lines[1:]:
                    if b":" in l:
                        k, v = l.split(b":", 1)
                        headers[k.strip().lower().decode()] = v.strip().decode()
                tls.sendall(on_request(path, headers))
        except (ssl.SSLError, OSError):
            pass
        finally:
            try: tls.close()
            except OSError: pass

    raw = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    raw.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    for attempt in range(20):
        try:
            raw.bind(("0.0.0.0", port)); break
        except OSError:
            if attempt == 19: raise
            time.sleep(0.2)
    raw.listen(8)

    def loop():
        while True:
            try:
                conn, _ = raw.accept()
            except OSError:
                return
            threading.Thread(target=handle, args=(conn,), daemon=True).start()

    threading.Thread(target=loop, daemon=True).start()
    return raw


def run_qemu(serial_path, typed_cmd):
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash", "-": "minus", ":": "shift-semicolon"}
        for ch in typed_cmd:
            s.sendall(("sendkey " + km.get(ch, ch) + "\n").encode()); time.sleep(0.12)
        # Scenario 3 does two full TLS 1.3 handshakes (origins A and B)
        # before settling -- confirmed by hand (same run, longer wait,
        # completes cleanly) to occasionally need more than the usual 25s
        # budget under emulation, the same margin session_cache_qemu.py
        # needed for the same reason.
        s.sendall(b"sendkey ret\n"); time.sleep(40)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-16x2-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    fails = 0
    srv = srvB = None
    try:
        pem, key, der = gen_cert(work)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1

        # ---- scenario 1: Basic auth ----
        observed = []
        # One long-lived server per port for the whole run (not one per
        # scenario): a thread blocked in accept() on a closed listening
        # socket doesn't reliably unblock on Linux, so a fresh bind to the
        # same port can fail with "Address already in use" even after
        # close() -- a real race hit while developing this test (same class
        # of bug keepalive_qemu.py's own comment documents). The handler is
        # swapped between scenarios instead of restarting the server.
        handler_a = {"fn": lambda path, headers: canned("404 Not Found", "no handler", "close")}
        handler_b = {"fn": lambda path, headers: canned("404 Not Found", "no handler", "close")}
        srv = start_server(443, pem, key, lambda path, headers: handler_a["fn"](path, headers))
        srvB = start_server(8443, pem, key, lambda path, headers: handler_b["fn"](path, headers))

        def on_basic(path, headers):
            observed.append(headers.get("authorization"))
            return canned("200 OK", "ok", "close")
        handler_a["fn"] = on_basic
        log = run_qemu(serial, "httpsget --auth-basic alice:s3cr3t 10.0.2.2 /basic %d" % int(time.time()))

        auth_hdr = observed[0] if observed else None
        decoded = None
        if auth_hdr and auth_hdr.startswith("Basic "):
            try:
                decoded = base64.b64decode(auth_hdr[6:]).decode()
            except Exception:
                decoded = None
        checks = [
            ("Basic: Authorization header observed", auth_hdr is not None),
            ("Basic: starts with \"Basic \"", auth_hdr is not None and auth_hdr.startswith("Basic ")),
            ("Basic: decodes to \"alice:s3cr3t\"", decoded == "alice:s3cr3t"),
            ("Basic: status=200 reached", "status=200" in log),
        ]

        # ---- scenario 2: Bearer auth ----
        observed2 = []
        def on_bearer(path, headers):
            observed2.append(headers.get("authorization"))
            return canned("200 OK", "ok", "close")
        handler_a["fn"] = on_bearer
        log2 = run_qemu(serial, "httpsget --auth-bearer mytoken123 10.0.2.2 /bearer %d" % int(time.time()))

        checks += [
            ("Bearer: exact header \"Bearer mytoken123\"", observed2 and observed2[0] == "Bearer mytoken123"),
            ("Bearer: status=200 reached", "status=200" in log2),
        ]

        # ---- scenario 3: credentials do not leak across a redirect to a different origin ----
        observedA, observedB = [], []
        def on_a(path, headers):
            observedA.append(headers.get("authorization"))
            return canned("302 Found", "go to B", "close", "https://10.0.2.2:8443/there")
        def on_b(path, headers):
            observedB.append(headers.get("authorization"))
            return canned("200 OK", "landed on B", "close")
        handler_a["fn"] = on_a
        handler_b["fn"] = on_b
        log3 = run_qemu(serial, "httpsget --auth-bearer secret999 10.0.2.2 /hop %d" % int(time.time()))
        srv.close(); srv = None
        srvB.close(); srvB = None

        checks += [
            ("Redirect scoping: origin A received the Bearer token", observedA and observedA[0] == "Bearer secret999"),
            ("Redirect scoping: origin B received NO Authorization header", observedB and observedB[0] is None),
            ("Redirect scoping: final response reached", "status=200" in log3 and "landed on B" in log3),
        ]

        for name, ok in checks:
            print(f"{name:55}: {'PASS' if ok else 'FAIL'}")
            if not ok: fails += 1
    finally:
        if srv:
            try: srv.close()
            except OSError: pass
        if srvB:
            try: srvB.close()
            except OSError: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n16.2 HTTP AUTHENTICATION (QEMU, real servers): " + ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
