#!/usr/bin/env python3
"""Embed a binary file as a C byte array.

Usage: bin2c.py <input-file> <symbol-name>  > output.c
"""
import sys

def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: bin2c.py <file> <symbol>\n")
        sys.exit(1)

    path, sym = sys.argv[1], sys.argv[2]
    with open(path, "rb") as f:
        data = f.read()

    out = sys.stdout
    out.write("/* Auto-generated by tools/bin2c.py. Do not edit. */\n")
    out.write("#include <stdint.h>\n\n")
    out.write(f"const unsigned char {sym}[] = {{\n")
    for i, b in enumerate(data):
        if i % 12 == 0:
            out.write("    ")
        out.write(f"0x{b:02x}, ")
        if i % 12 == 11:
            out.write("\n")
    out.write(f"\n}};\nconst unsigned int {sym}_len = {len(data)};\n")

if __name__ == "__main__":
    main()
