#!/usr/bin/env python3
"""Phase 15.9 acceptance: cookie jar persistence, negotiated for real inside
QEMU against a genuine TLS 1.3 server (Python's `ssl` module).

One QEMU boot, `httpsget 10.0.2.2 /login /profile /admin <now_unix>` (three
paths, Phase 15.4's multi-path CLI, one process, one kept-open connection):

  - /login: the server sends two Set-Cookie headers -- "session=xyz789;
    Path=/" (should apply everywhere) and "admin_token=secret777; Path=/admin"
    (should apply only under /admin). No cookie is sent on this first
    request (the jar starts empty).
  - /profile: the server inspects the REAL incoming Cookie header. It must
    contain "session=xyz789" (proving the jar persisted the cookie from
    /login and sent it back) and must NOT contain "admin_token" (proving
    RFC 6265 path scoping actually restricts what's sent, not just "send
    everything the jar has ever seen").
  - /admin: the server expects BOTH cookies here, since /admin is under the
    admin_token cookie's Path as well as the session cookie's Path=/.

Self-contained and reproducible: no private keys are committed; the
production user/ca_roots.h is restored on exit. Requires: qemu-system-i386,
openssl, the cross toolchain. Run from the repo root:
python3 tools/cookies_qemu.py
"""
import os, socket, ssl, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    key, pem, der = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem"), os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora Cookie Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by cookies_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def canned(body):
    b = body.encode()
    return f"HTTP/1.1 200 OK\r\nContent-Length: {len(b)}\r\n".encode() + b"Connection: keep-alive\r\n\r\n" + b


def start_server(port, certfile, keyfile):
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_3
    ctx.load_cert_chain(certfile=certfile, keyfile=keyfile)
    observed = []   # (path, cookie_header_or_None) in request order

    def handle(conn):
        try:
            tls = ctx.wrap_socket(conn, server_side=True)
        except (ssl.SSLError, OSError):
            conn.close(); return
        try:
            while True:
                buf = b""
                while b"\r\n\r\n" not in buf:
                    chunk = tls.recv(4096)
                    if not chunk:
                        return
                    buf += chunk
                head, _, rest = buf.partition(b"\r\n\r\n")
                lines = head.split(b"\r\n")
                path = lines[0].split(b" ")[1].decode()
                cookie_val = None
                for l in lines[1:]:
                    if l.lower().startswith(b"cookie:"):
                        cookie_val = l.split(b":", 1)[1].strip().decode()
                observed.append((path, cookie_val))

                if path == "/login":
                    resp = ("HTTP/1.1 200 OK\r\nContent-Length: 2\r\n"
                            "Set-Cookie: session=xyz789; Path=/\r\n"
                            "Set-Cookie: admin_token=secret777; Path=/admin\r\n"
                            "Connection: keep-alive\r\n\r\nok").encode()
                else:
                    resp = canned("ok")
                tls.sendall(resp)
        except (ssl.SSLError, OSError):
            pass
        finally:
            try: tls.close()
            except OSError: pass

    raw = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    raw.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    for attempt in range(20):
        try:
            raw.bind(("0.0.0.0", port)); break
        except OSError:
            if attempt == 19: raise
            time.sleep(0.2)
    raw.listen(8)

    def loop():
        while True:
            try:
                conn, _ = raw.accept()
            except OSError:
                return
            threading.Thread(target=handle, args=(conn,), daemon=True).start()

    threading.Thread(target=loop, daemon=True).start()
    return raw, observed


def run_qemu(serial_path, typed_cmd):
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash"}
        for ch in typed_cmd:
            s.sendall(("sendkey " + km.get(ch, ch) + "\n").encode()); time.sleep(0.12)
        s.sendall(b"sendkey ret\n"); time.sleep(25)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-15x9-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    fails = 0
    srv = None
    try:
        pem, key, der = gen_cert(work)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1

        srv, observed = start_server(443, pem, key)

        log = run_qemu(serial, "httpsget 10.0.2.2 /login /profile /admin %d" % int(time.time()))

        by_path = {}
        for path, cookie in observed:
            by_path.setdefault(path, cookie)   # first occurrence of each path

        login_cookie = by_path.get("/login")
        profile_cookie = by_path.get("/profile") or ""
        admin_cookie = by_path.get("/admin") or ""

        checks = [
            ("/login sent with no cookies (jar starts empty)", login_cookie is None),
            ("/profile sent the session cookie back", "session=xyz789" in profile_cookie),
            ("/profile did NOT send the /admin-scoped cookie (path scoping)",
             "admin_token" not in profile_cookie),
            ("/admin sent the session cookie", "session=xyz789" in admin_cookie),
            ("/admin sent the admin_token cookie (in scope here)", "admin_token=secret777" in admin_cookie),
            ("httpsget logged storing both Set-Cookie headers",
             "cookie stored: session=xyz789" in log and "cookie stored: admin_token=secret777" in log),
            ("all three requests got status=200", log.count("status=200") == 3),
        ]
        for name, ok in checks:
            print(f"{name:60}: {'PASS' if ok else 'FAIL'}")
            if not ok: fails += 1
    finally:
        if srv:
            try: srv.close()
            except OSError: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n15.9 COOKIE JAR (QEMU, real server): " + ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
