#!/usr/bin/env python3
"""Emit a C byte-array header for an X.509 certificate's DER.

Usage:  python3 tools/der2c.py <cert.pem|cert.der> [array_name] > out.h

Reads a certificate in PEM (------BEGIN CERTIFICATE-----) or raw DER form and
prints a `static const uint8_t <name>[] = { ... };` plus a `<name>_len`. Used to
embed a trust root into a userspace TLS program so the root needs no filesystem.
Pure Python: no openssl dependency, so it also works on the QEMU-side host.
"""
import sys, base64

def load_der(path):
    data = open(path, "rb").read()
    if b"-----BEGIN CERTIFICATE-----" in data:
        body = data.split(b"-----BEGIN CERTIFICATE-----", 1)[1]
        body = body.split(b"-----END CERTIFICATE-----", 1)[0]
        return base64.b64decode(b"".join(body.split()))
    return data  # already DER

def main():
    if len(sys.argv) < 2:
        sys.stderr.write(__doc__)
        sys.exit(2)
    path = sys.argv[1]
    name = sys.argv[2] if len(sys.argv) > 2 else "test_root_der"
    der = load_der(path)
    print("/* Generated by tools/der2c.py from %s -- do not edit by hand. */" % path)
    print("static const unsigned char %s[] = {" % name)
    for i in range(0, len(der), 12):
        row = ", ".join("0x%02x" % b for b in der[i:i+12])
        print("    %s," % row)
    print("};")
    print("static const unsigned %s_len = %d;" % (name, len(der)))

if __name__ == "__main__":
    main()
