#!/usr/bin/env python3
"""Rasterize a monospace TTF into an 8x16 1-bpp bitmap font -> kernel/font8x16.h.

Covers ASCII 32..126. Run once; the generated header is committed so the build
has no font dependency. (Regenerate: python3 tools/genfont.py)
"""
from PIL import Image, ImageFont, ImageDraw

FONT = "/mnt/skills/examples/canvas-design/canvas-fonts/IBMPlexMono-Regular.ttf"
CW, CH = 8, 16
SIZE = 14
X0, BASELINE = 0, 12
THRESH = 100

font = ImageFont.truetype(FONT, SIZE)
glyphs = []
for code in range(32, 127):
    img = Image.new("L", (CW, CH), 0)
    d = ImageDraw.Draw(img)
    d.text((X0, BASELINE), chr(code), fill=255, font=font, anchor="ls")
    rows = []
    for y in range(CH):
        b = 0
        for x in range(CW):
            if img.getpixel((x, y)) >= THRESH:
                b |= 1 << (7 - x)
        rows.append(b)
    glyphs.append((code, rows))

with open("kernel/font8x16.h", "w") as f:
    f.write("/* 8x16 bitmap font (ASCII 32..126), generated by tools/genfont.py.\n")
    f.write(" * Each glyph is 16 rows; bit 7 (0x80) is the leftmost pixel. */\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("#define FONT_W 8\n#define FONT_H 16\n#define FONT_FIRST 32\n#define FONT_LAST 126\n\n")
    f.write("static const uint8_t font8x16[%d][16] = {\n" % len(glyphs))
    for code, rows in glyphs:
        ch = chr(code) if code != 92 else "backslash"
        disp = chr(code).replace("*/", "")
        f.write("    { " + ", ".join("0x%02x" % b for b in rows) +
                " },  /* %3d '%s' */\n" % (code, disp))
    f.write("};\n")
print("wrote kernel/font8x16.h")
