#!/usr/bin/env python3
"""Phase 15.10 acceptance: gzip response decompression, negotiated for real
inside QEMU against a genuine TLS 1.3 server (Python's `ssl` module).

One QEMU boot, `httpsget 10.0.2.2 /a /b <now_unix>` (two paths, Phase 15.4's
multi-path CLI, one process -- no keep-alive needed here, each response says
"Connection: close"):

  - /a: the server inspects the REAL incoming request for "Accept-Encoding:
    gzip" (proving httpsget actually sent it, not just assuming the server
    would comply) and, finding it, answers with a genuine gzip-compressed
    body (Python's `gzip.compress`, Content-Encoding: gzip). httpsget must
    decompress it and show the *original* readable text in its preview, not
    the compressed bytes.
  - /b: a control case -- a plain, uncompressed response (no Content-
    Encoding at all) -- proving gzip support didn't break the plain path.

Self-contained and reproducible: no private keys are committed; the
production user/ca_roots.h is restored on exit. Requires: qemu-system-i386,
openssl, the cross toolchain. Run from the repo root:
python3 tools/gzip_qemu.py
"""
import gzip, os, socket, ssl, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GZIP_TEXT = ("Hello from a gzip-compressed HTTPS response! " * 20).encode()
PLAIN_TEXT = b"plain, uncompressed control response"


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    key, pem, der = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem"), os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora Gzip Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by gzip_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def start_server(port, certfile, keyfile):
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_3
    ctx.load_cert_chain(certfile=certfile, keyfile=keyfile)
    accept_encoding_seen = []   # records whether "gzip" was present, per request

    def handle(conn):
        try:
            tls = ctx.wrap_socket(conn, server_side=True)
        except (ssl.SSLError, OSError):
            conn.close(); return
        try:
            buf = b""
            while b"\r\n\r\n" not in buf:
                chunk = tls.recv(4096)
                if not chunk:
                    return
                buf += chunk
            head = buf.split(b"\r\n\r\n", 1)[0]
            lines = head.split(b"\r\n")
            path = lines[0].split(b" ")[1].decode()
            headers = {}
            for l in lines[1:]:
                if b":" in l:
                    k, v = l.split(b":", 1)
                    headers[k.strip().lower()] = v.strip()
            wants_gzip = b"gzip" in headers.get(b"accept-encoding", b"")

            if path == "/a":
                accept_encoding_seen.append(wants_gzip)
                if wants_gzip:
                    comp = gzip.compress(GZIP_TEXT, compresslevel=6)
                    resp = (f"HTTP/1.1 200 OK\r\nContent-Length: {len(comp)}\r\n"
                            f"Content-Encoding: gzip\r\nConnection: close\r\n\r\n").encode() + comp
                else:
                    resp = (f"HTTP/1.1 200 OK\r\nContent-Length: {len(GZIP_TEXT)}\r\n"
                            f"Connection: close\r\n\r\n").encode() + GZIP_TEXT
            else:
                resp = (f"HTTP/1.1 200 OK\r\nContent-Length: {len(PLAIN_TEXT)}\r\n"
                        f"Connection: close\r\n\r\n").encode() + PLAIN_TEXT
            tls.sendall(resp)
        except (ssl.SSLError, OSError):
            pass
        finally:
            try: tls.close()
            except OSError: pass

    raw = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    raw.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    for attempt in range(20):
        try:
            raw.bind(("0.0.0.0", port)); break
        except OSError:
            if attempt == 19: raise
            time.sleep(0.2)
    raw.listen(8)

    def loop():
        while True:
            try:
                conn, _ = raw.accept()
            except OSError:
                return
            threading.Thread(target=handle, args=(conn,), daemon=True).start()

    threading.Thread(target=loop, daemon=True).start()
    return raw, accept_encoding_seen


def run_qemu(serial_path, typed_cmd):
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash"}
        for ch in typed_cmd:
            s.sendall(("sendkey " + km.get(ch, ch) + "\n").encode()); time.sleep(0.12)
        s.sendall(b"sendkey ret\n"); time.sleep(25)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-15x10-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    fails = 0
    srv = None
    try:
        pem, key, der = gen_cert(work)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1

        srv, accept_encoding_seen = start_server(443, pem, key)

        log = run_qemu(serial, "httpsget 10.0.2.2 /a /b %d" % int(time.time()))

        segs = log.split("==== ")
        seg_a = next((s for s in segs if s.startswith("/a")), "")
        seg_b = next((s for s in segs if s.startswith("/b")), "")

        readable_text = "Hello from a gzip-compressed HTTPS response!"
        checks = [
            ("server received Accept-Encoding: gzip", accept_encoding_seen == [True]),
            ("/a: status=200", "status=200" in seg_a),
            ("/a: decompressed text is readable (not compressed bytes)", readable_text in seg_a),
            ("/a: body length reported matches the DECOMPRESSED size (900), not the wire size",
             ("[body %d bytes" % len(GZIP_TEXT)) in seg_a),
            ("/b (plain, uncompressed): status=200", "status=200" in seg_b),
            ("/b (plain, uncompressed): content shown as-is", "plain, uncompressed control response" in seg_b),
        ]
        for name, ok in checks:
            print(f"{name:70}: {'PASS' if ok else 'FAIL'}")
            if not ok: fails += 1
    finally:
        if srv:
            try: srv.close()
            except OSError: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n15.10 GZIP (QEMU, real server): " + ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
