#!/usr/bin/env python3
"""Phase 17.4.3 acceptance: HTTP/2 flow control (RFC 7540 §6.9), negotiated
for real inside QEMU against a genuine TLS 1.3 server that speaks real
HTTP/2 frames, hand-rolled here in Python -- independent of Aurora's own
http2/*.c, matching every other h2 QEMU test in this suite.

One QEMU boot: `httpsget --alpn 10.0.2.2 /big <now>` against a server that
answers with a 200000-byte body -- far larger than the RFC 7540 §6.9.2
default 65535-byte window, split across many DATA frames (each capped at
H2_FRAME_PAYLOAD_MAX, 16384 bytes, so the server MUST send more than three
just to clear the window once). Without real flow control, either the
server would eventually stop sending once Aurora's un-replenished window
hit zero (a real client would just hang waiting for bytes that are never
coming), or Aurora would have to just not enforce/track a window at all
(silently non-conformant, working today only because this test's server
happens to send everything regardless of window state). The server:

  1. Completes a minimal handshake (preface, SETTINGS exchange).
  2. Reads Aurora's request, then sends HEADERS + the WHOLE 200000-byte
     body as a sequence of DATA frames, END_STREAM on the last one.
  3. Afterward, reads back whatever WINDOW_UPDATE frames Aurora sent
     during the transfer (real ones, sent live as Aurora's own receive
     windows dropped, not just tolerated) and confirms: at least one
     targets the connection as a whole (stream_id 0) and at least one
     targets the specific stream (stream_id 1) -- Aurora is tracking BOTH
     windows independently, as RFC 7540 §6.9 requires, not just one.

Self-contained and reproducible: no private keys are committed; the
production user/ca_roots.h is restored on exit. Requires: qemu-system-i386,
openssl, the cross toolchain. Run from the repo root:
python3 tools/h2_flowctl_qemu.py
"""
import os, socket, ssl, struct, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

H2_PREFACE = b"PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"
H2_TYPE_DATA = 0
H2_TYPE_HEADERS = 1
H2_TYPE_SETTINGS = 4
H2_TYPE_WINDOW_UPDATE = 8
H2_FLAG_ACK = 1
H2_FLAG_END_STREAM = 1
H2_FLAG_END_HEADERS = 4
H2_FRAME_PAYLOAD_MAX = 16384

BODY_LEN = 200000   # far past the 65535-byte default window; needs 13 DATA frames at the 16384 cap


def hpack_encode_int(value, prefix_bits, flag_bits=0):
    max_prefix = (1 << prefix_bits) - 1
    if value < max_prefix:
        return bytes([flag_bits | value])
    out = bytearray([flag_bits | max_prefix])
    value -= max_prefix
    while value >= 128:
        out.append((value % 128) | 0x80)
        value //= 128
    out.append(value)
    return bytes(out)


def hpack_encode_string(s):
    b = s.encode("latin1")
    return hpack_encode_int(len(b), 7, 0x00) + b


def hpack_encode_literal_incremental(name_index, name, value):
    if name_index:
        out = hpack_encode_int(name_index, 6, 0x40)
    else:
        out = hpack_encode_int(0, 6, 0x40) + hpack_encode_string(name)
    return out + hpack_encode_string(value)


def h2_frame(type_, flags, stream_id, payload=b""):
    length = len(payload)
    return bytes([(length >> 16) & 0xFF, (length >> 8) & 0xFF, length & 0xFF,
                  type_, flags]) + struct.pack(">I", stream_id & 0x7FFFFFFF) + payload


def h2_parse_header(b9):
    length = (b9[0] << 16) | (b9[1] << 8) | b9[2]
    type_ = b9[3]
    flags = b9[4]
    stream_id = ((b9[5] & 0x7F) << 24) | (b9[6] << 16) | (b9[7] << 8) | b9[8]
    return length, type_, flags, stream_id


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    key, pem, der = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem"), os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora H2 Flow Control Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by h2_flowctl_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def start_server(port, certfile, keyfile, result):
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_3
    ctx.load_cert_chain(certfile=certfile, keyfile=keyfile)
    ctx.set_alpn_protocols(["h2"])
    result["window_updates"] = []

    def handle(conn):
        try:
            tls = ctx.wrap_socket(conn, server_side=True)
        except (ssl.SSLError, OSError):
            conn.close(); return
        result["alpn"] = tls.selected_alpn_protocol()
        tls.settimeout(10)
        buf = b""

        def recv_exact(n):
            nonlocal buf
            while len(buf) < n:
                chunk = tls.recv(65536)
                if not chunk:
                    raise OSError("connection closed")
                buf += chunk
            out, buf = buf[:n], buf[n:]
            return out

        def recv_h2_frame():
            hdr = recv_exact(9)
            length, type_, flags, stream_id = h2_parse_header(hdr)
            payload = recv_exact(length)
            return type_, flags, stream_id, payload

        try:
            preface = recv_exact(len(H2_PREFACE))
            result["preface_ok"] = (preface == H2_PREFACE)

            hdr = recv_exact(9)
            length, type_, _flags, _sid = h2_parse_header(hdr)
            recv_exact(length)
            result["client_settings_ok"] = (type_ == H2_TYPE_SETTINGS and length == 0)

            tls.sendall(h2_frame(H2_TYPE_SETTINGS, 0, 0))
            hdr2 = recv_exact(9)
            length2, type2, flags2, _s2 = h2_parse_header(hdr2)
            result["got_client_ack"] = (type2 == H2_TYPE_SETTINGS and flags2 == H2_FLAG_ACK and length2 == 0)
            tls.sendall(h2_frame(H2_TYPE_SETTINGS, H2_FLAG_ACK, 0))

            htype, hflags, hstream, hpayload = recv_h2_frame()
            result["request_ok"] = (htype == H2_TYPE_HEADERS and hstream == 1 and
                                    (hflags & H2_FLAG_END_HEADERS) != 0)

            headers = (
                hpack_encode_literal_incremental(8, None, "200") +
                hpack_encode_literal_incremental(31, None, "application/octet-stream")
            )
            tls.sendall(h2_frame(H2_TYPE_HEADERS, H2_FLAG_END_HEADERS, 1, headers))

            body = bytes(i % 256 for i in range(BODY_LEN))
            pos = 0
            while pos < len(body):
                chunk = body[pos:pos + H2_FRAME_PAYLOAD_MAX]
                pos += len(chunk)
                end_stream = pos >= len(body)
                flags = H2_FLAG_END_STREAM if end_stream else 0
                tls.sendall(h2_frame(H2_TYPE_DATA, flags, 1, chunk))
            result["data_frames_sent"] = (len(body) + H2_FRAME_PAYLOAD_MAX - 1) // H2_FRAME_PAYLOAD_MAX
            result["body_len_sent"] = len(body)

            # Drain whatever WINDOW_UPDATE frames Aurora sent back during
            # (or right after) the transfer, until the connection closes.
            while True:
                try:
                    wtype, _wflags, wstream, wpayload = recv_h2_frame()
                except (socket.timeout, OSError):
                    break
                if wtype == H2_TYPE_WINDOW_UPDATE and len(wpayload) == 4:
                    increment = ((wpayload[0] & 0x7F) << 24) | (wpayload[1] << 16) | (wpayload[2] << 8) | wpayload[3]
                    result["window_updates"].append((wstream, increment))
                # anything else (e.g. the connection simply closing) just ends the loop naturally
        except (socket.timeout, OSError, ssl.SSLError) as e:
            result["error"] = str(e)
        try: tls.close()
        except OSError: pass

    raw = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    raw.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    for attempt in range(20):
        try:
            raw.bind(("0.0.0.0", port)); break
        except OSError:
            if attempt == 19: raise
            time.sleep(0.2)
    raw.listen(8)

    def loop():
        while True:
            try:
                conn, _ = raw.accept()
            except OSError:
                return
            threading.Thread(target=handle, args=(conn,), daemon=True).start()

    threading.Thread(target=loop, daemon=True).start()
    return raw


def run_qemu(serial_path, typed_cmd, wait_s=45):
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash", "-": "minus"}
        def key_for(ch):
            if ch in km: return km[ch]
            if ch.isupper(): return "shift-" + ch.lower()
            return ch
        for ch in typed_cmd:
            s.sendall(("sendkey " + key_for(ch) + "\n").encode()); time.sleep(0.12)
        s.sendall(b"sendkey ret\n"); time.sleep(wait_s)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-17x4x3-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    fails = 0
    srv = None
    try:
        pem, key, der = gen_cert(work)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1

        result = {}
        srv = start_server(443, pem, key, result)

        log = run_qemu(serial, "httpsget --alpn 10.0.2.2 /big %d" % int(time.time()))

        wus = result.get("window_updates", [])
        conn_level = [inc for sid, inc in wus if sid == 0]
        stream_level = [inc for sid, inc in wus if sid == 1]

        checks = [
            ("ALPN negotiated \"h2\"", result.get("alpn") == "h2"),
            ("server received the exact connection preface", result.get("preface_ok") is True),
            ("server confirms the client's SETTINGS is real and empty", result.get("client_settings_ok") is True),
            ("server confirms it received the client's SETTINGS ACK", result.get("got_client_ack") is True),
            ("server confirms a real HEADERS request arrived on stream 1", result.get("request_ok") is True),
            ("server sent the response as more than 3 DATA frames (the 16384-byte frame cap forces this "
             "for a 200000-byte body)", result.get("data_frames_sent", 0) > 3),
            ("server received at least one CONNECTION-level WINDOW_UPDATE (stream 0)", len(conn_level) >= 1),
            ("server received at least one STREAM-level WINDOW_UPDATE (stream 1)", len(stream_level) >= 1),
            ("every received WINDOW_UPDATE increment is positive and RFC-plausible (<= 65535)",
             all(0 < inc <= 65535 for _sid, inc in wus)),
            ("client log shows more than one WINDOW_UPDATE actually sent (a single large response "
             "needs several, not just one)", log.count("WINDOW_UPDATE sent") > 1),
            ("client log shows BOTH a connection-level (stream 0) and stream-level (stream 1) "
             "WINDOW_UPDATE were sent", "WINDOW_UPDATE sent (stream 0," in log and "WINDOW_UPDATE sent (stream 1," in log),
            ("client log shows the FULL 200000-byte body was received (not silently truncated at the "
             "flow-control layer)", ("%d body bytes" % BODY_LEN) in log),
            ("client log shows status=200 reached", "status=200" in log),
            ("client log shows the final 200 OK line", "200 OK over Aurora TCP->TLS1.3->HTTP" in log),
            ("no error was recorded server-side", "error" not in result),
        ]

        for name, ok in checks:
            print(f"{name:80}: {'PASS' if ok else 'FAIL'}")
            if not ok: fails += 1
    finally:
        if srv:
            try: srv.close()
            except OSError: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n17.4.3 HTTP/2 FLOW CONTROL (QEMU, real frame-level server): " +
          ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
