#!/usr/bin/env python3
"""Phase 17.1.1/17.1.2 acceptance: the HTTP/2 connection-establishment
handshake (RFC 7540 §3.5/§6.5) plus the generic frame reader and DATA frame
support (17.1.2), negotiated for real inside QEMU against a genuine TLS 1.3
server that speaks real HTTP/2 frames at the byte level (hand-rolled here in
Python, independent of Aurora's own http2/frame.c -- this script's frame
encoder is a from-scratch second implementation, not a copy, so a bug
shared between the two wouldn't hide behind agreement).

One QEMU boot: `httpsget --alpn 10.0.2.2 /whatever <now>` against a server
whose own ALPN list is `["h2"]` only, forcing the selection (this script
only cares about the h2 path -- see tools/alpn_qemu.py for the ALPN
selection matrix itself). The server:

  1. Reads the connection preface (24 bytes) and confirms it's exactly
     "PRI * HTTP/2.0\\r\\n\\r\\nSM\\r\\n\\r\\n" -- not just "some bytes arrived".
  2. Reads the client's SETTINGS frame and confirms it's really type=
     SETTINGS, non-ACK, empty (Aurora's own choice: no special preferences).
  3. Sends its OWN SETTINGS frame back -- deliberately non-empty (one real
     parameter), unlike Aurora's, to prove the client's frame reader
     correctly skips an arbitrary-length payload, not just a zero-length
     one -- followed immediately by a WINDOW_UPDATE frame (a connection-
     level flow-control bump many real HTTP/2 servers send unprompted right
     after their SETTINGS), to prove Aurora's "skip anything that isn't one
     of the two frames it's waiting for" logic really does tolerate an
     unrelated frame type interleaved in the middle of the exchange, not
     just extra bytes of a *known* type.
  4. Sends a stray, PADDED, END_STREAM DATA frame on a stream nothing ever
     opened (Phase 17.1.2): this is the real point of this step -- the
     generic frame reader now decodes a genuine, payload-bearing, padded
     frame type correctly (Aurora's own log names it: "DATA frame seen"),
     not just tolerates extra bytes of a frame type it already recognized
     like the WINDOW_UPDATE above.
  5. Waits for Aurora's SETTINGS ACK (type=SETTINGS, flags=ACK, empty) and
     confirms it arrives.
  6. Sends its own SETTINGS ACK, acknowledging Aurora's SETTINGS from step 2.
  7. Confirms NO further bytes ever arrive afterward -- there is still no
     HEADERS framing, so even though the connection-establishment handshake
     just completed successfully (having correctly parsed a real DATA frame
     along the way), there is still no way for Aurora to actually send a
     request over it, and it should say so and stop, not send anything else.

Self-contained and reproducible: no private keys are committed; the
production user/ca_roots.h is restored on exit. Requires: qemu-system-i386,
openssl, the cross toolchain. Run from the repo root:
python3 tools/h2_handshake_qemu.py
"""
import os, socket, ssl, struct, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

H2_PREFACE = b"PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"
H2_TYPE_DATA = 0
H2_TYPE_SETTINGS = 4
H2_TYPE_WINDOW_UPDATE = 8
H2_FLAG_ACK = 1
H2_FLAG_END_STREAM = 1
H2_FLAG_PADDED = 8


def h2_frame(type_, flags, stream_id, payload=b""):
    length = len(payload)
    return bytes([(length >> 16) & 0xFF, (length >> 8) & 0xFF, length & 0xFF,
                  type_, flags]) + struct.pack(">I", stream_id & 0x7FFFFFFF) + payload


def h2_data_frame(stream_id, data, padding=0, end_stream=False):
    """A real, padded DATA frame (RFC 7540 SS6.1): [pad_len][data][padding]."""
    flags = (H2_FLAG_END_STREAM if end_stream else 0) | (H2_FLAG_PADDED if padding else 0)
    payload = (bytes([padding]) if padding else b"") + data + (b"\x00" * padding)
    return h2_frame(H2_TYPE_DATA, flags, stream_id, payload)


def h2_parse_header(b9):
    length = (b9[0] << 16) | (b9[1] << 8) | b9[2]
    type_ = b9[3]
    flags = b9[4]
    stream_id = ((b9[5] & 0x7F) << 24) | (b9[6] << 16) | (b9[7] << 8) | b9[8]
    return length, type_, flags, stream_id


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    key, pem, der = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem"), os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora H2 Handshake Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by h2_handshake_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def start_server(port, certfile, keyfile, result):
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_3
    ctx.load_cert_chain(certfile=certfile, keyfile=keyfile)
    ctx.set_alpn_protocols(["h2"])   # only h2 available -- forces the selection

    def handle(conn):
        try:
            tls = ctx.wrap_socket(conn, server_side=True)
        except (ssl.SSLError, OSError):
            conn.close(); return
        result["alpn"] = tls.selected_alpn_protocol()
        tls.settimeout(10)
        buf = b""

        def recv_exact(n):
            nonlocal buf
            while len(buf) < n:
                chunk = tls.recv(4096)
                if not chunk:
                    raise OSError("connection closed mid-handshake")
                buf += chunk
            out, buf = buf[:n], buf[n:]
            return out

        try:
            preface = recv_exact(len(H2_PREFACE))
            result["preface_ok"] = (preface == H2_PREFACE)

            hdr = recv_exact(9)
            length, type_, flags, _stream_id = h2_parse_header(hdr)
            recv_exact(length)   # the (empty) SETTINGS payload itself
            result["client_settings_ok"] = (type_ == H2_TYPE_SETTINGS and flags == 0 and length == 0)

            # Our own SETTINGS: deliberately non-empty (one real parameter --
            # SETTINGS_MAX_CONCURRENT_STREAMS=100), to prove the client skips
            # an arbitrary-length payload correctly, not just a zero-length one.
            settings_payload = struct.pack(">HI", 0x3, 100)
            tls.sendall(h2_frame(H2_TYPE_SETTINGS, 0, 0, settings_payload))
            # A connection-level WINDOW_UPDATE right after SETTINGS, unprompted
            # -- common in real servers, and exactly the "frame type the client
            # isn't specifically waiting for" case its skip logic needs to
            # tolerate mid-handshake, not just before or after it.
            tls.sendall(h2_frame(H2_TYPE_WINDOW_UPDATE, 0, 0, struct.pack(">I", 65535)))
            # A stray, PADDED, END_STREAM DATA frame on a stream nothing ever
            # opened (Phase 17.1.2's whole point: the generic frame reader now
            # decodes a real, payload-bearing, padded frame type correctly --
            # not just tolerates extra bytes of a frame type it already knew
            # about, like the empty SETTINGS/WINDOW_UPDATE above).
            tls.sendall(h2_data_frame(1, b"unsolicited body", padding=5, end_stream=True))

            hdr2 = recv_exact(9)
            length2, type2, flags2, _s2 = h2_parse_header(hdr2)
            result["got_client_ack"] = (type2 == H2_TYPE_SETTINGS and flags2 == H2_FLAG_ACK and length2 == 0)

            # Acknowledge the client's own SETTINGS.
            tls.sendall(h2_frame(H2_TYPE_SETTINGS, H2_FLAG_ACK, 0))

            # Nothing more should ever arrive: no HEADERS/DATA framing exists
            # in this phase, so Aurora should stop right here.
            try:
                extra = tls.recv(4096)
            except (socket.timeout, ssl.SSLError, OSError):
                extra = b""
            result["extra_after_handshake"] = extra
        except (socket.timeout, OSError, ssl.SSLError) as e:
            result["error"] = str(e)
        try: tls.close()
        except OSError: pass

    raw = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    raw.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    for attempt in range(20):
        try:
            raw.bind(("0.0.0.0", port)); break
        except OSError:
            if attempt == 19: raise
            time.sleep(0.2)
    raw.listen(8)

    def loop():
        while True:
            try:
                conn, _ = raw.accept()
            except OSError:
                return
            threading.Thread(target=handle, args=(conn,), daemon=True).start()

    threading.Thread(target=loop, daemon=True).start()
    return raw


def run_qemu(serial_path, typed_cmd, wait_s=25):
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash", "-": "minus"}
        def key_for(ch):
            if ch in km: return km[ch]
            if ch.isupper(): return "shift-" + ch.lower()
            return ch
        for ch in typed_cmd:
            s.sendall(("sendkey " + key_for(ch) + "\n").encode()); time.sleep(0.12)
        s.sendall(b"sendkey ret\n"); time.sleep(wait_s)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-17x1x1-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    fails = 0
    srv = None
    try:
        pem, key, der = gen_cert(work)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1

        result = {}
        srv = start_server(443, pem, key, result)

        log = run_qemu(serial, "httpsget --alpn 10.0.2.2 /whatever %d" % int(time.time()))

        checks = [
            ("ALPN negotiated \"h2\"", result.get("alpn") == "h2"),
            ("server received the exact 24-byte connection preface", result.get("preface_ok") is True),
            ("server confirms the client's SETTINGS is real (type=SETTINGS, non-ACK, empty)",
             result.get("client_settings_ok") is True),
            ("client log shows the preface + SETTINGS were sent",
             "connection preface + SETTINGS sent" in log),
            ("client log shows the server's SETTINGS was received",
             "server SETTINGS received" in log),
            ("client log shows the stray padded DATA frame was correctly recognized as DATA "
             "(not confused with the WINDOW_UPDATE or SETTINGS around it)",
             "DATA frame seen (stream 1," in log),
            ("client log shows our SETTINGS ACK was sent", "SETTINGS ACK sent" in log),
            ("server confirms it actually received that SETTINGS ACK", result.get("got_client_ack") is True),
            ("client log shows the server's SETTINGS ACK (for ours) was recognized",
             "our SETTINGS was ACKed" in log),
            ("client log shows the connection-establishment handshake completed",
             "connection-establishment handshake complete" in log),
            ("client log shows it still can't fetch a request yet (no HEADERS/DATA framing)",
             "HEADERS/DATA framing is not implemented yet" in log),
            ("status=200 was never reached (no request was ever sent)", "status=200" not in log),
            ("server confirms NOTHING further arrived after the handshake completed",
             result.get("extra_after_handshake") == b""),
            ("no error was recorded server-side", "error" not in result),
        ]

        for name, ok in checks:
            print(f"{name:80}: {'PASS' if ok else 'FAIL'}")
            if not ok: fails += 1
    finally:
        if srv:
            try: srv.close()
            except OSError: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n17.1.1 HTTP/2 CONNECTION-ESTABLISHMENT HANDSHAKE (QEMU, real frame-level server): " +
          ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
