#!/usr/bin/env python3
"""Phase 17.5.2 acceptance (item 3, "interoperability"): a real, unmodified
nginx (not a hand-rolled Python peer, unlike every other h2 QEMU test in
this suite) serving genuine HTTP/2 over TLS 1.3, fetched for real inside
QEMU. Every other test in this project's h2_*_qemu.py family deliberately
controls both ends of the wire to pin down exactly which byte Aurora sent
or received -- this one instead asks the opposite question: does Aurora
work against a widely-deployed, independently-implemented HTTP/2 server
that makes its own choices about framing, SETTINGS values, and TLS
parameters, choices nobody on this project made?

nginx (Ubuntu package, `apt-get install nginx`, not started via systemd --
this test launches its own instance with its own self-contained config, so
it never touches the system's default site or log files) serves:

  1. /small.txt -- a short, fixed text file: the baseline "does a real GET
     over real nginx-negotiated h2 work at all" check.
  2. /big.bin -- a 300000-byte file (past the 200000-byte size 17.4.3's
     own flow-control test already proved against a hand-rolled peer) --
     proving flow control also holds against nginx's OWN DATA-frame
     chunking and timing, which this project doesn't control.
  Both fetched over ONE reused connection (Phase 17.4.2), the same as
  every multi-path h2 test in this suite.

Self-contained and reproducible: nginx runs from a throwaway config in a
tempdir (own error/access logs, own pid file, no systemctl, no touching
/etc/nginx's own sites-enabled), killed on exit. No private keys are
committed; the production user/ca_roots.h is restored on exit. Requires:
qemu-system-i386, openssl, nginx (built with --with-http_v2_module -- the
stock Ubuntu package is), the cross toolchain. Run from the repo root:
python3 tools/h2_nginx_interop_qemu.py
"""
import os, re, signal, socket, subprocess, sys, tempfile, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BIG_LEN = 300000


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    key, pem, der = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem"), os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora H2 nginx Interop Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by h2_nginx_interop_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def find_nginx():
    for candidate in ("/usr/sbin/nginx", "/usr/local/sbin/nginx", shutil.which("nginx")):
        if candidate and os.path.exists(candidate):
            return candidate
    return None


def start_nginx(work, pem, key):
    webroot = os.path.join(work, "www")
    os.makedirs(webroot, exist_ok=True)
    small_body = b"Aurora HTTP/2 <-> nginx interop OK\n"
    big_body = bytes(i % 256 for i in range(BIG_LEN))
    open(os.path.join(webroot, "small.txt"), "wb").write(small_body)
    open(os.path.join(webroot, "big.bin"), "wb").write(big_body)

    pidfile = os.path.join(work, "nginx.pid")
    conf = os.path.join(work, "nginx.conf")
    # `user root` -- tempfile.mkdtemp() makes `work` mode 0700 (owner-only),
    # and nginx's worker processes otherwise drop privileges to its
    # compiled-in default user (www-data on Ubuntu), which then can't even
    # traverse into `work` to serve the files below (a real 403 this test
    # hit once already). This whole server only lives for one test run as
    # a throwaway peer -- there's no separate, less-privileged user to drop
    # to that would mean anything here, unlike a real deployment.
    open(conf, "w").write(f"""
daemon off;
pid {pidfile};
error_log {os.path.join(work, "error.log")} info;
user root;
events {{ worker_connections 64; }}
http {{
    access_log off;
    server {{
        listen 443 ssl http2;
        server_name 10.0.2.2;
        ssl_certificate {pem};
        ssl_certificate_key {key};
        ssl_protocols TLSv1.3;
        root {webroot};
    }}
}}
""")
    nginx_bin = find_nginx()
    if not nginx_bin:
        raise RuntimeError("nginx not found -- 'apt-get install nginx' first")
    p = subprocess.Popen([nginx_bin, "-c", conf], cwd=work,
                         stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    # Wait for the real listening socket, not just process start.
    for _ in range(50):
        try:
            s = socket.create_connection(("127.0.0.1", 443), timeout=0.5)
            s.close()
            break
        except OSError:
            time.sleep(0.2)
    else:
        p.terminate()
        raise RuntimeError("nginx never started listening on :443")
    return p, small_body, big_body


def run_qemu(serial_path, typed_cmd, wait_s=60):
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash", "-": "minus"}
        def key_for(ch):
            if ch in km: return km[ch]
            if ch.isupper(): return "shift-" + ch.lower()
            return ch
        for ch in typed_cmd:
            s.sendall(("sendkey " + key_for(ch) + "\n").encode()); time.sleep(0.12)
        s.sendall(b"sendkey ret\n"); time.sleep(wait_s)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=5)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-17x5x2-nginx-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    fails = 0
    nginx_proc = None
    try:
        pem, key, der = gen_cert(work)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1

        nginx_proc, small_body, big_body = start_nginx(work, pem, key)

        log = run_qemu(os.path.join(work, "serial.log"),
                       "httpsget --alpn 10.0.2.2 /small.txt /big.bin %d" % int(time.time()))

        checks = [
            ("ALPN negotiated \"h2\" against real nginx", "h2: connection-establishment handshake complete" in log),
            ("client log shows only ONE TCP connection was ever made", log.count("TCP connected to 10.0.2.2") == 1),
            ("client log shows the connection reused for /big.bin", "reusing open connection to 10.0.2.2" in log),
            ("client log shows stream 1 (/small.txt) completed", "stream 1 complete" in log),
            ("client log shows stream 3 (/big.bin) completed", "stream 3 complete" in log),
            ("/small.txt: exact body content received from real nginx",
             small_body.decode().strip() in log),
            ("/big.bin: exact byte count received (%d bytes) from real nginx's own DATA framing" % BIG_LEN,
             ("%d body bytes)" % BIG_LEN) in log),
            ("client log shows status=200 reached for both real nginx responses",
             log.count("response bytes, status=200") == 2),
            ("client log shows the final 200 OK line", "200 OK over Aurora TCP->TLS1.3->HTTP" in log),
            ("no HPACK/frame-level error against nginx's own encoder", "HPACK decode failed" not in log and
             "malformed" not in log.lower()),
        ]

        for name, ok in checks:
            print(f"{name:100}: {'PASS' if ok else 'FAIL'}")
            if not ok: fails += 1
    finally:
        if nginx_proc:
            try:
                nginx_proc.send_signal(signal.SIGTERM)
                nginx_proc.wait(timeout=5)
            except Exception:
                try: nginx_proc.kill()
                except Exception: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n17.5.2 HTTP/2 INTEROPERABILITY vs real nginx (QEMU): " +
          ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
