#!/usr/bin/env python3
"""Phase 15.4 acceptance: HTTP keep-alive, negotiated for real inside QEMU
against a persistent-connection TLS server, over Aurora's own TLS 1.3 stack.

Three scenarios, each a fresh QEMU boot, each `httpsget 10.0.2.2 <path> <path>`
(two or three paths, one process, Phase 15.4's multi-path CLI). Handshake
count is checked via "TCP connected to" (printed once per fresh connection)
rather than "[TLS] CONNECTED", which is printed TWICE per real handshake --
once by the trace_sink event, once by httpsget's own status line -- and would
silently double the count if used directly:
  1. server says "Connection: keep-alive" for every response -> ONE TCP
     connection serves all requests ("reusing open connection" appears twice).
  2. server says "Connection: close" on the first response -> a SECOND, fresh
     connection is required for the next path (no "reusing" line).
  3. server says "keep-alive" but then actually closes anyway (a realistic
     race: a short server-side idle timeout) -> httpsget's optimistic reuse
     hits a dead write/read, logs "already closed -- reconnecting", and
     completes the second request over a fresh connection.

A custom Python `ssl`-based TLS server is used here (not openssl s_server,
whose -HTTP/-WWW modes always close after exactly one request no matter what
Connection: says -- verified by hand before writing this test -- so they can't
serve a real persistent-connection exchange). This doesn't need any special
cipher/group configuration: Aurora's ClientHello offers exactly one cipher
suite (TLS_CHACHA20_POLY1305_SHA256) and one group (X25519), so any compliant
TLS 1.3 server converges on them regardless of its own preference order.

Self-contained and reproducible: no private keys are committed; the
production user/ca_roots.h is restored on exit. Requires: qemu-system-i386,
openssl, the cross toolchain. Run from the repo root:
python3 tools/keepalive_qemu.py
"""
import os, socket, ssl, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    key, pem, der = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem"), os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora Keepalive Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by keepalive_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def canned(body, connection):
    b = body.encode()
    return (f"HTTP/1.1 200 OK\r\nContent-Length: {len(b)}\r\nConnection: {connection}\r\n\r\n").encode() + b


def start_server(port, certfile, keyfile, routes):
    """routes: path -> (response_bytes, linger_after_send).
    linger_after_send=True: keep reading more requests on the same TLS
    connection (a well-behaved keep-alive server). False: close the raw
    socket right after sending, regardless of what the response header said
    (models both an honest "Connection: close" and a server that claims
    keep-alive but drops the connection anyway -- scenario 3)."""
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_3
    ctx.load_cert_chain(certfile=certfile, keyfile=keyfile)

    def handle(conn):
        try:
            tls = ctx.wrap_socket(conn, server_side=True)
        except (ssl.SSLError, OSError):
            conn.close(); return
        buf = b""
        try:
            while True:
                while b"\r\n\r\n" not in buf:
                    chunk = tls.recv(4096)
                    if not chunk:
                        return
                    buf += chunk
                head, _, buf = buf.partition(b"\r\n\r\n")
                path = head.split(b"\r\n")[0].split(b" ")[1].decode()
                resp, linger = routes.get(path, (canned("not found", "close"), False))
                tls.sendall(resp)
                if not linger:
                    return
        except (ssl.SSLError, OSError):
            return
        finally:
            try: tls.close()
            except OSError: pass

    raw = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    raw.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    for attempt in range(20):
        try:
            raw.bind(("0.0.0.0", port)); break
        except OSError:
            if attempt == 19: raise
            time.sleep(0.2)
    raw.listen(8)

    def loop():
        while True:
            try:
                conn, _ = raw.accept()
            except OSError:
                return
            threading.Thread(target=handle, args=(conn,), daemon=True).start()

    threading.Thread(target=loop, daemon=True).start()
    return raw


def run_qemu(serial_path, typed_cmd):
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash"}
        for ch in typed_cmd:
            s.sendall(("sendkey " + km.get(ch, ch) + "\n").encode()); time.sleep(0.12)
        s.sendall(b"sendkey ret\n"); time.sleep(25)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-15x4-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    fails = 0
    srv = None
    try:
        pem, key, der = gen_cert(work)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1

        # One server for the whole run (not one per scenario): a thread blocked
        # in accept() on a closed listening socket doesn't reliably unblock on
        # Linux, so the port can appear to stay bound well after close() -- a
        # real race hit while developing this test. Every scenario's paths are
        # distinct strings, so a single combined routes table works fine.
        routes = {
            "/a": (canned("AAAA", "keep-alive"), True),
            "/b": (canned("BBBB", "keep-alive"), True),
            "/c": (canned("CCCC", "keep-alive"), True),
            "/x": (canned("XXXX", "close"), False),
            "/y": (canned("YYYY", "keep-alive"), True),
            "/p": (canned("PPPP", "keep-alive"), False),   # says keep-alive, then drops the connection anyway
            "/q": (canned("QQQQ", "keep-alive"), True),
        }
        srv = start_server(443, pem, key, routes)

        # Count fresh connections via "TCP connected to" (printed exactly once
        # per fetch_begin() call) rather than "[TLS] CONNECTED" -- that string
        # is printed TWICE per real handshake (once by the trace_sink event,
        # once by httpsget's own explicit status line), which would silently
        # double-count and defeat the point of the assertion.
        cases = [
            ("reuse across 3 paths", "httpsget 10.0.2.2 /a /b /c",
             lambda log: log.count("TCP connected to") == 1 and log.count("reusing open connection") == 2
                         and log.count("status=200") == 3),
            ("Connection: close forces reconnect", "httpsget 10.0.2.2 /x /y",
             lambda log: log.count("TCP connected to") == 2 and "reusing open connection" not in log
                         and log.count("status=200") == 2),
            ("stale reused connection recovers", "httpsget 10.0.2.2 /p /q",
             lambda log: log.count("TCP connected to") == 2 and "already closed -- reconnecting" in log
                         and log.count("status=200") == 2),
        ]
        for name, cmd, ok_fn in cases:
            log = run_qemu(serial, cmd + " %d" % int(time.time()))
            ok = ok_fn(log)
            line = next((l for l in log.splitlines() if "reusing" in l or "already closed" in l or "status=" in l), "(no result)")
            print(f"{name:32}: {'PASS' if ok else 'FAIL'}  {line.strip()}")
            if not ok: fails += 1
    finally:
        if srv:
            try: srv.close()
            except OSError: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n15.4 KEEP-ALIVE (QEMU, validation ON): " + ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
