#!/usr/bin/env python3
"""Phase 16.5 acceptance: the general --method mechanism (PUT/DELETE/HEAD),
negotiated for real inside QEMU against a genuine TLS 1.3 server (Python's
`ssl` module).

Three scenarios, each a fresh QEMU boot (one long-lived server across all
three, per this suite's usual pattern for avoiding a QEMU port-reuse race):

  1. `httpsget --method PUT 10.0.2.2 /item newvalue123` -- the server
     inspects the REAL incoming request and confirms method=PUT and the
     exact body bytes, proving --method's body-bearing branch (shared code
     with --post) works for a method other than POST.
  2. `httpsget --method DELETE 10.0.2.2 /item123` -- the server confirms
     method=DELETE and that NO body/Content-Length was sent at all.
  3. `httpsget --method HEAD 10.0.2.2 /big` -- the critical one. The server
     answers with `Content-Length: 999999` (as a real server would, describing
     what a GET to /big would return) and `Connection: keep-alive`, but sends
     ZERO actual body bytes -- exactly what RFC 7230 SS3.3.3 says a real HEAD
     response looks like, and exactly the case that would make an
     un-special-cased client's read loop block forever waiting for 999999
     bytes that are never coming, since the server (like a real one) does
     NOT close the connection afterward -- it loops back to wait for the
     NEXT request, same as any keep-alive exchange. If httpsget's HEAD fix
     (the g_no_body path in resp_feed()/fetch_request()) weren't in place,
     this scenario would hang until the QEMU wait budget is exhausted and
     "status=200" would simply never appear in the log; the fix is what
     makes this finish quickly instead.

Self-contained and reproducible: no private keys are committed; the
production user/ca_roots.h is restored on exit. Requires: qemu-system-i386,
openssl, the cross toolchain. Run from the repo root: python3 tools/method_qemu.py
"""
import os, socket, ssl, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    key, pem, der = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem"), os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora Method Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by method_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def canned(status, body, connection, location=None):
    b = body.encode()
    loc = f"Location: {location}\r\n" if location else ""
    return (f"HTTP/1.1 {status}\r\n{loc}Content-Length: {len(b)}\r\n"
            f"Connection: {connection}\r\n\r\n").encode() + b


def head_response(fake_content_length, connection):
    # A real server's response to HEAD: headers exactly as if for the
    # equivalent GET (including a Content-Length describing that GET's real
    # body), but literally zero body bytes -- the RFC 7230 SS3.3.3 case this
    # phase's g_no_body fix exists for.
    return (f"HTTP/1.1 200 OK\r\nContent-Length: {fake_content_length}\r\n"
            f"Connection: {connection}\r\n\r\n").encode()


def start_server(port, certfile, keyfile, on_request):
    """on_request(method, path, headers_dict, body_bytes) -> response bytes."""
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_3
    ctx.load_cert_chain(certfile=certfile, keyfile=keyfile)

    def handle(conn):
        try:
            tls = ctx.wrap_socket(conn, server_side=True)
        except (ssl.SSLError, OSError):
            conn.close(); return
        buf = b""
        try:
            while True:
                while b"\r\n\r\n" not in buf:
                    chunk = tls.recv(4096)
                    if not chunk:
                        return
                    buf += chunk
                head, _, buf = buf.partition(b"\r\n\r\n")
                lines = head.split(b"\r\n")
                method, path = lines[0].split(b" ")[0].decode(), lines[0].split(b" ")[1].decode()
                headers = {}
                for l in lines[1:]:
                    if b":" in l:
                        k, v = l.split(b":", 1)
                        headers[k.strip().lower().decode()] = v.strip().decode()
                clen = int(headers.get("content-length", "0"))
                while len(buf) < clen:
                    chunk = tls.recv(4096)
                    if not chunk:
                        return
                    buf += chunk
                body, buf = buf[:clen], buf[clen:]
                tls.sendall(on_request(method, path, headers, body))
        except (ssl.SSLError, OSError):
            pass
        finally:
            try: tls.close()
            except OSError: pass

    raw = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    raw.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    for attempt in range(20):
        try:
            raw.bind(("0.0.0.0", port)); break
        except OSError:
            if attempt == 19: raise
            time.sleep(0.2)
    raw.listen(8)

    def loop():
        while True:
            try:
                conn, _ = raw.accept()
            except OSError:
                return
            threading.Thread(target=handle, args=(conn,), daemon=True).start()

    threading.Thread(target=loop, daemon=True).start()
    return raw


def run_qemu(serial_path, typed_cmd, wait_s=25):
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash", "-": "minus"}
        def key_for(ch):
            if ch in km: return km[ch]
            if ch.isupper(): return "shift-" + ch.lower()
            return ch
        for ch in typed_cmd:
            s.sendall(("sendkey " + key_for(ch) + "\n").encode()); time.sleep(0.12)
        # A normal single-request scenario needs no more than the usual 25s;
        # deliberately NOT bumped for scenario 3 (HEAD) -- if the hang-
        # prevention fix were missing, that scenario should time out within
        # this same ordinary budget and fail visibly, not be masked by a
        # generously long wait.
        s.sendall(b"sendkey ret\n"); time.sleep(wait_s)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-16x5-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    fails = 0
    srv = None
    try:
        pem, key, der = gen_cert(work)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1

        # One long-lived server across all three scenarios, handler swapped
        # between them -- see auth_qemu.py's own comment for why (a thread
        # blocked in accept() on a closed listening socket doesn't reliably
        # unblock on Linux, so restarting the server per scenario risks
        # "Address already in use" on the next bind).
        handler = {"fn": lambda m, p, h, b: canned("404 Not Found", "no handler", "close")}
        srv = start_server(443, pem, key, lambda m, p, h, b: handler["fn"](m, p, h, b))

        # ---- scenario 1: PUT with a real body ----
        observed = []
        def on_put(m, p, h, b):
            observed.append((m, p, h, b))
            return canned("200 OK", "put ok", "close")
        handler["fn"] = on_put
        log1 = run_qemu(serial, "httpsget --method PUT 10.0.2.2 /item newvalue123 %d" % int(time.time()))

        put_req = observed[0] if observed else None
        checks = [
            ("PUT: request observed", put_req is not None),
            ("PUT: method is PUT", put_req and put_req[0] == "PUT"),
            ("PUT: exact body bytes received", put_req and put_req[3] == b"newvalue123"),
            ("PUT: Content-Length matches the real body length",
             put_req and put_req[2].get("content-length") == str(len(put_req[3]))),
            ("PUT: status=200 reached", "status=200" in log1),
        ]

        # ---- scenario 2: DELETE, bodyless ----
        observed2 = []
        def on_delete(m, p, h, b):
            observed2.append((m, p, h, b))
            return canned("200 OK", "deleted", "close")
        handler["fn"] = on_delete
        log2 = run_qemu(serial, "httpsget --method DELETE 10.0.2.2 /item123 %d" % int(time.time()))

        del_req = observed2[0] if observed2 else None
        checks += [
            ("DELETE: request observed", del_req is not None),
            ("DELETE: method is DELETE", del_req and del_req[0] == "DELETE"),
            ("DELETE: no body/Content-Length sent",
             del_req and "content-length" not in del_req[2] and del_req[3] == b""),
            ("DELETE: status=200 reached", "status=200" in log2),
        ]

        # ---- scenario 3: HEAD -- the RFC 7230 SS3.3.3 hang-prevention case ----
        observed3 = []
        def on_head(m, p, h, b):
            observed3.append((m, p, h, b))
            return head_response(999999, "keep-alive")
        handler["fn"] = on_head
        log3 = run_qemu(serial, "httpsget --method HEAD 10.0.2.2 /big %d" % int(time.time()))

        head_req = observed3[0] if observed3 else None
        checks += [
            ("HEAD: request observed", head_req is not None),
            ("HEAD: method is HEAD", head_req and head_req[0] == "HEAD"),
            ("HEAD: did not hang -- status=200 reached within the normal wait budget despite "
             "a fake 999999-byte Content-Length", "status=200" in log3),
        ]

        for name, ok in checks:
            print(f"{name:85}: {'PASS' if ok else 'FAIL'}")
            if not ok: fails += 1
    finally:
        if srv:
            try: srv.close()
            except OSError: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n16.5 HTTP METHODS incl. HEAD hang-prevention (QEMU, real server): " +
          ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
