#!/usr/bin/env python3
"""Phase 16.4 acceptance: multipart/form-data, negotiated for real inside
QEMU against a genuine TLS 1.3 server (Python's `ssl` module).

One QEMU boot: `httpsget --post-multipart 10.0.2.2 /upload name=alice
file=@/disk/UPLOAD.TXT <now>`

  - /upload: the server extracts the boundary from the REAL incoming
    Content-Type header and parses the REAL multipart body itself (its own
    parser, not trusting httpsget's "sent" log line) into parts, checking:
    a plain text part ("name" -> "alice") and a file part ("file", whose
    filename is UPLOAD.TXT's own basename, Content-Type
    application/octet-stream, and body bytes matching EXACTLY what was
    baked onto disk.img -- proving open()/read() of a real FAT32 file made
    it into the wire body byte-for-byte). It responds 307 Temporary
    Redirect to /upload2, to also exercise Phase 16.3's redirect machinery
    on a multipart body specifically.
  - /upload2: 307 must preserve method, body AND Content-Type (this is the
    new part Phase 16.4 adds to fetch_one()'s per-hop state); the server
    checks the second request's Content-Type string -- boundary included --
    is byte-identical to /upload's, and that the raw body bytes are
    byte-identical too, before ending the chain with 200 OK.

UPLOAD.TXT is not a permanent repo file: it's generated fresh into a temp
dir and baked onto disk.img directly via tools/mkfat32.py (replicating the
Makefile's own file list plus this one extra entry), so nothing new lands
in the repository.

Self-contained and reproducible: no private keys are committed; the
production user/ca_roots.h AND disk.img are both restored on exit. Requires:
qemu-system-i386, openssl, the cross toolchain. Run from the repo root:
python3 tools/multipart_qemu.py
"""
import os, re, socket, ssl, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UPLOAD_CONTENT = b"Aurora multipart upload test payload.\nSecond line.\n"

# Same NAME/src pairs as the Makefile's $(DISK) rule, plus one extra entry
# (UPLOAD.TXT) this test needs baked onto the disk image for httpsget to
# open()/read() -- kept here rather than touching the Makefile itself.
DISK_ENTRIES = [
    ("INIT.ELF", "user/init.elf"), ("LOGGER.ELF", "user/logger.elf"),
    ("SH.ELF", "user/sh.elf"), ("HELLO.ELF", "user/hello.elf"),
    ("CAT.ELF", "user/cat.elf"), ("GREP.ELF", "user/grep.elf"), ("ORPHAN.ELF", "user/orphan.elf"),
    ("NETD.ELF", "user/netd.elf"), ("ECHOSRV.ELF", "user/echosrv.elf"), ("ECHOCLI.ELF", "user/echocli.elf"),
    ("SAVE.ELF", "user/save.elf"), ("WSERVER.ELF", "user/wserver.elf"), ("TERM.ELF", "user/term.elf"),
    ("DOCK.ELF", "user/dock.elf"), ("FILES.ELF", "user/files.elf"), ("VIEWER.ELF", "user/viewer.elf"),
    ("ABOUT.TXT", "user/about.txt"), ("POEM.TXT", "user/poem.txt"), ("WMSTRESS.ELF", "user/wmstress.elf"),
    ("SETTINGS.ELF", "user/settings.elf"), ("FETCH.ELF", "user/fetch.elf"),
    ("TLSCONN.ELF", "user/tlsconnect.elf"), ("HTTPSGET.ELF", "user/httpsget.elf"),
]


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    key, pem, der = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem"), os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora Multipart Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by multipart_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def build_disk_with_upload(work):
    upload_path = os.path.join(work, "upload.txt")
    with open(upload_path, "wb") as f:
        f.write(UPLOAD_CONTENT)
    args = ["python3", "tools/mkfat32.py", "disk.img"]
    for name, src in DISK_ENTRIES:
        args += [name, src]
    args += ["UPLOAD.TXT", upload_path]
    r = subprocess.run(args, cwd=ROOT, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
    return r.returncode == 0


def canned(status, body, connection, location=None):
    b = body.encode()
    loc = f"Location: {location}\r\n" if location else ""
    return (f"HTTP/1.1 {status}\r\n{loc}Content-Length: {len(b)}\r\n"
            f"Connection: {connection}\r\n\r\n").encode() + b


def extract_boundary(ctype):
    m = re.search(r'boundary=([^;]+)', ctype or "")
    return m.group(1).strip() if m else None


def parse_content_disposition(v):
    name = None
    filename = None
    m = re.search(r'name="([^"]*)"', v)
    if m: name = m.group(1)
    m = re.search(r'filename="([^"]*)"', v)
    if m: filename = m.group(1)
    return name, filename


def parse_multipart(body, boundary):
    delim = b"--" + boundary.encode()
    segs = body.split(delim)
    parts = {}
    for seg in segs[1:-1]:
        if seg.startswith(b"\r\n"): seg = seg[2:]
        if seg.endswith(b"\r\n"): seg = seg[:-2]
        hdr_end = seg.find(b"\r\n\r\n")
        if hdr_end < 0: continue
        headers_raw = seg[:hdr_end].decode(errors="replace")
        data = seg[hdr_end + 4:]
        cdisp, ctype = "", ""
        for line in headers_raw.split("\r\n"):
            if ":" in line:
                k, v = line.split(":", 1)
                k = k.strip().lower(); v = v.strip()
                if k == "content-disposition": cdisp = v
                elif k == "content-type": ctype = v
        name, filename = parse_content_disposition(cdisp)
        parts[name] = {"filename": filename, "content_type": ctype, "data": data}
    return parts


def start_server(port, certfile, keyfile):
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_3
    ctx.load_cert_chain(certfile=certfile, keyfile=keyfile)
    observed = {}   # path -> {content_type, body, parts}

    def handle(conn):
        try:
            tls = ctx.wrap_socket(conn, server_side=True)
        except (ssl.SSLError, OSError):
            conn.close(); return
        buf = b""
        try:
            while True:
                while b"\r\n\r\n" not in buf:
                    chunk = tls.recv(4096)
                    if not chunk:
                        return
                    buf += chunk
                head, _, buf = buf.partition(b"\r\n\r\n")
                lines = head.split(b"\r\n")
                path = lines[0].split(b" ")[1].decode()
                headers = {}
                for l in lines[1:]:
                    if b":" in l:
                        k, v = l.split(b":", 1)
                        headers[k.strip().lower().decode()] = v.strip().decode()
                clen = int(headers.get("content-length", "0"))
                while len(buf) < clen:
                    chunk = tls.recv(4096)
                    if not chunk:
                        return
                    buf += chunk
                body, buf = buf[:clen], buf[clen:]

                ctype = headers.get("content-type", "")
                boundary = extract_boundary(ctype)
                parts = parse_multipart(body, boundary) if boundary else None
                observed[path] = {"content_type": ctype, "body": body, "parts": parts}

                if path == "/upload":
                    resp = canned("307 Temporary Redirect", "go to upload2", "keep-alive", "/upload2")
                elif path == "/upload2":
                    resp = canned("200 OK", "multipart chain complete", "close")
                else:
                    resp = canned("404 Not Found", "not found", "close")
                tls.sendall(resp)
        except (ssl.SSLError, OSError):
            pass
        finally:
            try: tls.close()
            except OSError: pass

    raw = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    raw.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    for attempt in range(20):
        try:
            raw.bind(("0.0.0.0", port)); break
        except OSError:
            if attempt == 19: raise
            time.sleep(0.2)
    raw.listen(8)

    def loop():
        while True:
            try:
                conn, _ = raw.accept()
            except OSError:
                return
            threading.Thread(target=handle, args=(conn,), daemon=True).start()

    threading.Thread(target=loop, daemon=True).start()
    return raw, observed


def run_qemu(serial_path, typed_cmd):
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash", "=": "equal", "&": "shift-7",
              "-": "minus", "@": "shift-2"}
        # UPLOAD.TXT's uppercase 8.3 name is the first typed command in this
        # test suite with uppercase ASCII letters: QEMU's HMP "sendkey" takes
        # qcode names for physical keys (always lowercase, e.g. "u"), not the
        # shifted glyph -- typing the literal uppercase character "U" isn't a
        # recognized key name and is silently dropped, not rejected, which
        # first showed up here as "UPLOAD.TXT" arriving on the guest as just
        # "." (every uppercase letter vanished, only the dot survived).
        def key_for(ch):
            if ch in km: return km[ch]
            if ch.isupper(): return "shift-" + ch.lower()
            return ch
        for ch in typed_cmd:
            s.sendall(("sendkey " + key_for(ch) + "\n").encode()); time.sleep(0.12)
        # /upload -> /upload2 is a same-origin 307, so this is one full TLS
        # handshake plus one keep-alive-reused request -- comparable to
        # redirect_preserve_qemu.py's lighter chain, 35s gives margin.
        s.sendall(b"sendkey ret\n"); time.sleep(35)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-16x4-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    fails = 0
    srv = None
    try:
        pem, key, der = gen_cert(work)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf").returncode != 0:
            print("build FAILED"); return 1
        if not build_disk_with_upload(work):
            print("disk.img build (with UPLOAD.TXT) FAILED"); return 1

        srv, observed = start_server(443, pem, key)

        log = run_qemu(serial, "httpsget --post-multipart 10.0.2.2 /upload name=alice "
                               "file=@/disk/UPLOAD.TXT %d" % int(time.time()))

        up1 = observed.get("/upload")
        up2 = observed.get("/upload2")
        p1 = up1["parts"] if up1 else None
        p2 = up2["parts"] if up2 else None

        checks = [
            ("/upload request observed", up1 is not None),
            ("/upload: Content-Type is multipart/form-data with a boundary",
             up1 and up1["content_type"].startswith("multipart/form-data; boundary=")),
            ("/upload: exactly 2 parts parsed", p1 is not None and len(p1) == 2),
            ("/upload: text field 'name' == 'alice'",
             p1 and p1.get("name") and p1["name"]["data"] == b"alice" and p1["name"]["filename"] is None),
            ("/upload: file field 'file' has filename UPLOAD.TXT",
             p1 and p1.get("file") and (p1["file"]["filename"] or "").upper().endswith("UPLOAD.TXT")),
            ("/upload: file field Content-Type is application/octet-stream",
             p1 and p1.get("file") and p1["file"]["content_type"] == "application/octet-stream"),
            ("/upload: file field bytes match the real on-disk file exactly",
             p1 and p1.get("file") and p1["file"]["data"] == UPLOAD_CONTENT),
            ("307 redirect to /upload2 observed", "307 redirect -> /upload2" in log),
            ("/upload2 request observed", up2 is not None),
            ("/upload2: Content-Type identical to /upload's (boundary preserved across 307)",
             up1 and up2 and up1["content_type"] == up2["content_type"]),
            ("/upload2: raw body bytes identical to /upload's (Phase 16.3 preservation)",
             up1 and up2 and up1["body"] == up2["body"]),
            ("chain completed, status=200", "status=200" in log and "multipart chain complete" in log),
        ]
        for name, ok in checks:
            print(f"{name:65}: {'PASS' if ok else 'FAIL'}")
            if not ok: fails += 1
    finally:
        if srv:
            try: srv.close()
            except OSError: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        # disk.img is a *.img build artifact (gitignored, never tracked) --
        # nothing to `git checkout` back to. It was just rebuilt directly via
        # mkfat32.py (bypassing make) with an extra UPLOAD.TXT entry, which
        # would make it look newer than its prerequisites to `make`'s
        # timestamp check and get skipped -- remove it first so the Makefile
        # rule actually regenerates the normal (no-UPLOAD.TXT) image.
        try: os.remove(os.path.join(ROOT, "disk.img"))
        except OSError: pass
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n16.4 MULTIPART/FORM-DATA (QEMU, real server): " + ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
