#!/usr/bin/env python3
"""Phase 15.2 acceptance: HTTP redirect following INSIDE QEMU, over Aurora's own
DNS -> TCP -> TLS 1.3 -> HTTP/1.1 stack, with certificate validation ON.

Three scenarios, each a fresh QEMU boot:
  1. same-host HTTPS->HTTPS redirect (301, absolute-path Location) -> 200
  2. cross-scheme HTTPS->HTTP redirect (302, absolute URI Location) -> 200,
     proving the plain-HTTP transport branch and the scheme/port switch in
     user/url.c actually run inside the freestanding environment, not just in
     the host-side url-test unit tests
  3. a two-hop redirect cycle -> "redirect loop detected", proving the
     visited-URL loop guard fires before the MAX_REDIRECTS ceiling would

The TLS leg is served by `openssl s_server -HTTP` (raw canned HTTP responses,
including custom status lines / Location headers -- -www/-WWW always force
"200 ok" and can't produce a redirect). A single self-signed P-256 cert acts as
both the leaf Aurora receives and the trust anchor installed in its store: a
self-signed leaf whose subject exactly matches a configured root verifies in
one step (x509_verify_chain), so chain-building depth isn't this test's
concern -- that's already covered by 14.x.7 and 15.1. The HTTP leg (no TLS) is
a tiny raw-socket responder in this script.

Self-contained and reproducible: no private keys are committed; the production
user/ca_roots.h is restored on exit. Requires: qemu-system-i386, openssl, the
cross toolchain. Run from the repo root: python3 tools/redirects_qemu.py
"""
import os, socket, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    """A single self-signed ECDSA P-256 cert, SAN=DNS:10.0.2.2 -- used as both
    the TLS leaf and (installed separately) the sole trust root."""
    key, pem = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem")
    der = os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora Redirect Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by redirects_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def write_webroot(webroot):
    files = {
        "start":  "HTTP/1.1 301 Moved Permanently\r\nLocation: /next\r\nContent-Length: 0\r\nConnection: close\r\n\r\n",
        "next":   "HTTP/1.1 200 OK\r\nContent-Length: 2\r\nConnection: close\r\n\r\nOK",
        "switch": "HTTP/1.1 302 Found\r\nLocation: http://10.0.2.2/plain\r\nContent-Length: 0\r\nConnection: close\r\n\r\n",
        "loopa":  "HTTP/1.1 301 Moved Permanently\r\nLocation: /loopb\r\nContent-Length: 0\r\nConnection: close\r\n\r\n",
        "loopb":  "HTTP/1.1 301 Moved Permanently\r\nLocation: /loopa\r\nContent-Length: 0\r\nConnection: close\r\n\r\n",
    }
    os.makedirs(webroot, exist_ok=True)
    for name, content in files.items():
        open(os.path.join(webroot, name), "w", newline="").write(content)


def plain_http_server():
    """Minimal raw-socket HTTP/1.1 responder on :80 for the cross-scheme hop
    (no TLS). Serves a canned 200 for /plain, 404 otherwise. Daemon thread."""
    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srv.bind(("0.0.0.0", 80)); srv.listen(8)

    def loop():
        while True:
            try:
                conn, _ = srv.accept()
            except OSError:
                return
            try:
                conn.settimeout(5)
                req = conn.recv(4096)
                path = req.split(b" ", 2)[1] if b" " in req else b"/"
                if path == b"/plain":
                    body = b"HTTP/1.1 200 OK\r\nContent-Length: 8\r\nConnection: close\r\n\r\nPLAIN-OK"
                else:
                    body = b"HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\nConnection: close\r\n\r\n"
                conn.sendall(body)
            except OSError:
                pass
            finally:
                conn.close()

    t = threading.Thread(target=loop, daemon=True)
    t.start()
    return srv


def run_qemu(serial_path, typed_cmd):
    """Boot Aurora text-mode, type `typed_cmd`, capture serial."""
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash"}
        for ch in typed_cmd:
            s.sendall(("sendkey " + km.get(ch, ch) + "\n").encode()); time.sleep(0.12)
        s.sendall(b"sendkey ret\n"); time.sleep(25)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-15x2-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    webroot = os.path.join(work, "webroot")
    fails = 0
    srv443 = srv80 = None
    try:
        pem, key, der = gen_cert(work)
        write_webroot(webroot)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1

        srv443 = subprocess.Popen(
            ["openssl", "s_server", "-accept", "443", "-cert", pem, "-key", key,
             "-HTTP", "-tls1_3", "-ciphersuites", "TLS_CHACHA20_POLY1305_SHA256",
             "-groups", "X25519", "-quiet"],
            cwd=webroot, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        srv80 = plain_http_server()
        time.sleep(1)

        cases = [
            ("same-host redirect", "httpsget 10.0.2.2 /start",
             lambda log: "301 redirect -> /next" in log and "status=200" in log
                         and "after redirects" in log),
            ("cross-scheme redirect", "httpsget 10.0.2.2 /switch",
             lambda log: "302 redirect -> http://10.0.2.2/plain" in log
                         and "GET /plain HTTP/1.1 sent (plain HTTP)" in log and "status=200" in log),
            ("redirect loop detection", "httpsget 10.0.2.2 /loopa",
             lambda log: "redirect loop detected" in log),
        ]
        for name, cmd, ok_fn in cases:
            log = run_qemu(serial, cmd)
            ok = ok_fn(log)
            line = next((l for l in log.splitlines() if "redirect" in l or "status=" in l), "(no result)")
            print(f"{name:24}: {'PASS' if ok else 'FAIL'}  {line.strip()}")
            if not ok: fails += 1
    finally:
        if srv443:
            srv443.terminate()
            try: srv443.wait(timeout=3)
            except subprocess.TimeoutExpired: srv443.kill()
        if srv80:
            try: srv80.close()
            except OSError: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n15.2 REDIRECTS (QEMU, validation ON): " + ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
