#!/usr/bin/env python3
"""Phase 16.3 acceptance: RFC 7231/7238-correct redirect handling for a
request with a body, negotiated for real inside QEMU against a genuine
TLS 1.3 server (Python's `ssl` module).

One QEMU boot, a four-hop chain that exercises every status-code rule in
one run: `httpsget --post 10.0.2.2 /start name=alice&age=30 <now>`

  - /start (POST, real body) -- responds 307, redirect to /mid. 307 MUST
    preserve the method and body: the server checks /mid's request really
    is a POST with the identical body bytes.
  - /mid (expected POST, same body) -- responds 308, redirect to /late.
    308 has the same preserve-method-and-body rule as 307 (RFC 7238); the
    server checks /late's request is still POST with the same body, having
    now passed through two preserving hops in a row.
  - /late (expected POST, same body) -- responds 302, redirect to /final.
    302 is NOT a preserving status: even though the request arrived at
    /late as a POST (via two 307/308 hops), the *next* hop must downgrade
    to a bodyless GET -- proving the decision is made fresh per redirect
    response, not "once POST always POST for the rest of the chain."
  - /final (expected GET, no body) -- 200 OK, ending the chain.

Self-contained and reproducible: no private keys are committed; the
production user/ca_roots.h is restored on exit. Requires: qemu-system-i386,
openssl, the cross toolchain. Run from the repo root:
python3 tools/redirect_preserve_qemu.py
"""
import os, socket, ssl, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    key, pem, der = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem"), os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora Redirect Preserve Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by redirect_preserve_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def canned(status, body, connection, location=None):
    b = body.encode()
    loc = f"Location: {location}\r\n" if location else ""
    return (f"HTTP/1.1 {status}\r\n{loc}Content-Length: {len(b)}\r\n"
            f"Connection: {connection}\r\n\r\n").encode() + b


def start_server(port, certfile, keyfile):
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_3
    ctx.load_cert_chain(certfile=certfile, keyfile=keyfile)
    observed = []   # (method, path, headers_dict, body_bytes) in request order

    routes = {
        "/start": ("307 Temporary Redirect", "go to mid", "/mid"),
        "/mid":   ("308 Permanent Redirect", "go to late", "/late"),
        "/late":  ("302 Found", "go to final", "/final"),
        "/final": ("200 OK", "chain complete", None),
    }

    def handle(conn):
        try:
            tls = ctx.wrap_socket(conn, server_side=True)
        except (ssl.SSLError, OSError):
            conn.close(); return
        buf = b""
        try:
            while True:
                while b"\r\n\r\n" not in buf:
                    chunk = tls.recv(4096)
                    if not chunk:
                        return
                    buf += chunk
                head, _, buf = buf.partition(b"\r\n\r\n")
                lines = head.split(b"\r\n")
                method, path = lines[0].split(b" ")[0].decode(), lines[0].split(b" ")[1].decode()
                headers = {}
                for l in lines[1:]:
                    if b":" in l:
                        k, v = l.split(b":", 1)
                        headers[k.strip().lower().decode()] = v.strip().decode()
                clen = int(headers.get("content-length", "0"))
                while len(buf) < clen:
                    chunk = tls.recv(4096)
                    if not chunk:
                        return
                    buf += chunk
                body, buf = buf[:clen], buf[clen:]
                observed.append((method, path, headers, body))

                status, msg, location = routes.get(path, ("404 Not Found", "not found", None))
                tls.sendall(canned(status, msg, "keep-alive" if location else "close", location))
        except (ssl.SSLError, OSError):
            pass
        finally:
            try: tls.close()
            except OSError: pass

    raw = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    raw.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    for attempt in range(20):
        try:
            raw.bind(("0.0.0.0", port)); break
        except OSError:
            if attempt == 19: raise
            time.sleep(0.2)
    raw.listen(8)

    def loop():
        while True:
            try:
                conn, _ = raw.accept()
            except OSError:
                return
            threading.Thread(target=handle, args=(conn,), daemon=True).start()

    threading.Thread(target=loop, daemon=True).start()
    return raw, observed


def run_qemu(serial_path, typed_cmd):
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash", "=": "equal", "&": "shift-7", "-": "minus"}
        for ch in typed_cmd:
            s.sendall(("sendkey " + km.get(ch, ch) + "\n").encode()); time.sleep(0.12)
        # A four-hop chain (one full handshake plus three keep-alive-reused
        # requests) is more round trips than most single-command tests in
        # this suite; 35s gives comfortable margin under emulation.
        s.sendall(b"sendkey ret\n"); time.sleep(35)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-16x3-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    fails = 0
    srv = None
    try:
        pem, key, der = gen_cert(work)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1

        srv, observed = start_server(443, pem, key)

        log = run_qemu(serial, "httpsget --post 10.0.2.2 /start name=alice&age=30 %d" % int(time.time()))

        by_path = {}
        for method, path, headers, body in observed:
            by_path.setdefault(path, (method, headers, body))

        start = by_path.get("/start")
        mid = by_path.get("/mid")
        late = by_path.get("/late")
        final = by_path.get("/final")
        orig_body = b"name=alice&age=30"

        checks = [
            ("/start: original POST with the real body", start and start[0] == "POST" and start[2] == orig_body),
            ("307 redirect observed", "307 redirect -> /mid" in log),
            ("/mid: 307 preserved method (POST)", mid and mid[0] == "POST"),
            ("/mid: 307 preserved the exact body", mid and mid[2] == orig_body),
            ("308 redirect observed", "308 redirect -> /late" in log),
            ("/late: 308 preserved method (POST)", late and late[0] == "POST"),
            ("/late: 308 preserved the exact body", late and late[2] == orig_body),
            ("302 redirect observed", "302 redirect -> /final" in log),
            ("/final: 302 downgraded to GET (not sticky-POST)", final and final[0] == "GET"),
            ("/final: no body/Content-Length carried over", final and "content-length" not in final[1]),
            ("chain completed, status=200", "status=200" in log and "chain complete" in log),
        ]
        for name, ok in checks:
            print(f"{name:55}: {'PASS' if ok else 'FAIL'}")
            if not ok: fails += 1
    finally:
        if srv:
            try: srv.close()
            except OSError: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n16.3 REDIRECT METHOD/BODY PRESERVATION (QEMU, real server): " +
          ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
