#!/usr/bin/env python3
"""Phase 14.x.7 acceptance: secure HTTPS 200 OK INSIDE QEMU, certificate
validation ON, over a fully controlled depth-N PKI (Root CA -> Intermediate ->
Leaf) for RSA, ECDSA P-256 and ECDSA P-384.

For each key type this regenerates a fresh chain (leaf SAN dNSName 10.0.2.2),
installs the test Root CA into Aurora's trust store, builds httpsget, serves the
leaf+intermediate from a local TLS 1.3 server (ChaCha20-Poly1305 + X25519) reached
via SLIRP at 10.0.2.2:443, boots Aurora text-mode in QEMU, runs
`httpsget 10.0.2.2 /`, and checks the serial for a 200 with the full
chain-OK / CertificateVerify-OK / CONNECTED trace.

Self-contained and reproducible: no private keys are committed (the PKI is
generated on each run); the production user/ca_roots.h is restored on exit.
Requires: qemu-system-i386, openssl, the cross toolchain (i.e. `make`).
Run from the repo root:  python3 tools/securehttps_qemu.py
"""
import os, socket, subprocess, sys, tempfile, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALGOS = ["rsa", "p256", "p384"]


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_chain(work, algo):
    """Generate Root->Intermediate->Leaf for `algo`; return (root_der, chain_pem, leaf_key)."""
    d = os.path.join(work, algo); os.makedirs(d, exist_ok=True)
    md = "sha384" if algo == "p384" else "sha256"
    def key(out):
        if algo == "rsa": sh(f"openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out {out}")
        elif algo == "p256": sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {out}")
        else: sh(f"openssl ecparam -name secp384r1 -genkey -noout -out {out}")
    bc_ca = "basicConstraints=critical,CA:TRUE"; ku_ca = "keyUsage=critical,keyCertSign,cRLSign"
    key(f"{d}/root.key")
    sh(f'openssl req -x509 -new -key {d}/root.key -{md} -days 1000 -out {d}/root.pem '
       f'-subj "/CN=Aurora Test Root {algo}" -addext "{bc_ca}" -addext "{ku_ca}"')
    key(f"{d}/inter.key")
    sh(f'openssl req -new -key {d}/inter.key -out {d}/inter.csr -subj "/CN=Aurora Test Intermediate {algo}"')
    ext_i = f"{d}/ext_i"; open(ext_i, "w").write("basicConstraints=critical,CA:TRUE,pathlen:0\nkeyUsage=critical,keyCertSign,cRLSign\n")
    sh(f"openssl x509 -req -in {d}/inter.csr -CA {d}/root.pem -CAkey {d}/root.key -CAcreateserial -{md} -days 1000 -out {d}/inter.pem -extfile {ext_i}")
    key(f"{d}/leaf.key")
    sh(f'openssl req -new -key {d}/leaf.key -out {d}/leaf.csr -subj "/CN=10.0.2.2"')
    ext_l = f"{d}/ext_l"; open(ext_l, "w").write("basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature\nsubjectAltName=DNS:10.0.2.2\n")
    sh(f"openssl x509 -req -in {d}/leaf.csr -CA {d}/inter.pem -CAkey {d}/inter.key -CAcreateserial -{md} -days 1000 -out {d}/leaf.pem -extfile {ext_l}")
    sh(f"openssl x509 -in {d}/root.pem -outform DER -out {d}/root.der")
    return f"{d}/root.der", f"{d}/leaf.pem", f"{d}/inter.pem", f"{d}/leaf.key"


def write_trust_header(path, root_ders):
    out = ["/* GENERATED by securehttps_qemu.py -- test roots only, NOT committed. */", "#pragma once"]
    table = []
    for i, der in enumerate(root_ders):
        b = open(der, "rb").read()
        out.append(f"static const unsigned char ca_root_{i}[] = {{")
        out.append("    " + ",".join(str(x) for x in b))
        out.append("};")
        table.append(f'    {{ ca_root_{i}, {len(b)}, "test root {i}" }},')
    out.append("static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {")
    out += table
    out.append("};")
    out.append("#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])")
    open(path, "w").write("\n".join(out) + "\n")


def run_qemu(serial_path):
    """Boot Aurora text-mode, type `httpsget 10.0.2.2 / <now>`, capture serial.

    The trailing `<now>` is the actual current unix time: httpsget's built-in
    HTTPSGET_NOW default is a fixed compile-time constant, and this harness's
    certs are generated with notBefore = whenever openssl actually runs, so a
    long-running session (or a rebuild days later) can otherwise drift past
    the default and spuriously fail with "leaf not yet valid" -- a test-harness
    timing artifact, not a real validation bug. Passing the live clock removes
    the drift entirely; httpsget itself never gains a wall clock from this."""
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash"}
        cmd = "httpsget 10.0.2.2 / %d" % int(time.time())
        for ch in cmd:
            s.sendall(("sendkey " + km.get(ch, ch) + "\n").encode()); time.sleep(0.12)
        s.sendall(b"sendkey ret\n"); time.sleep(25)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-14x7-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    fails = 0
    try:
        chains = {a: gen_chain(work, a) for a in ALGOS}
        write_trust_header(prod, [chains[a][0] for a in ALGOS])      # all 3 test roots
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1
        for a in ALGOS:
            _, leaf, inter, leafkey = chains[a]
            srv = subprocess.Popen(
                ["openssl", "s_server", "-accept", "443", "-cert", leaf, "-key", leafkey,
                 "-cert_chain", inter, "-tls1_3", "-ciphersuites", "TLS_CHACHA20_POLY1305_SHA256",
                 "-groups", "X25519", "-www", "-quiet"],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            time.sleep(1)
            log = run_qemu(serial)
            srv.terminate()
            try: srv.wait(timeout=3)
            except subprocess.TimeoutExpired: srv.kill()
            ok = ("Certificate chain OK" in log and "CertificateVerify OK" in log
                  and "[TLS] CONNECTED" in log and "status=200" in log)
            line = next((l for l in log.splitlines() if "status=" in l or "TLS FAILED" in l), "(no result)")
            print(f"{a:5}: {'PASS' if ok else 'FAIL'}  {line.strip()}")
            if not ok: fails += 1
    finally:
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n14.x.7 SECURE HTTPS (QEMU, validation ON): " + ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
