#!/usr/bin/env python3
"""Phase 15.8 acceptance: multi-origin session cache, negotiated for real
inside QEMU against two genuine TLS 1.3 servers (Python's `ssl` module) on
different ports of the same host -- two distinct origins.

One QEMU boot, `httpsget 10.0.2.2 /starta <now_unix>`, following a redirect
chain entirely on its own (Phase 15.2):

  1. /starta on :443 (origin A) -- a full handshake (first-ever connection).
     The response is a 302 redirect to :8443 (origin B) with
     "Connection: keep-alive" and a determinate length, so httpsget's own
     15.4 reuse policy leaves origin A's slot connection OPEN rather than
     closing it just because the *next* request targets a different origin.
  2. /hop on :8443 (origin B) -- a second full handshake, a different slot.
     Redirects back to :443 (default https port, so no port in the URL).
  3. /finish on :443 (origin A again) -- proves the point: without a
     multi-origin cache, switching to B would have closed A's connection
     (the pre-15.8 code did exactly that in fetch()'s "else" branch), and
     coming back would cost a second full handshake. With the cache, A's
     slot still has its connection open from step 1, so this is served with
     *zero* TLS activity at all -- no new TCP connection, no handshake, not
     even an abbreviated one.

Self-contained and reproducible: no private keys are committed; the
production user/ca_roots.h is restored on exit. Requires: qemu-system-i386,
openssl, the cross toolchain. Run from the repo root:
python3 tools/session_cache_qemu.py
"""
import os, socket, ssl, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    key, pem, der = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem"), os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora Session Cache Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by session_cache_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def canned(status, body, connection, location=None):
    b = body.encode()
    loc = f"Location: {location}\r\n" if location else ""
    return (f"HTTP/1.1 {status}\r\n{loc}Content-Length: {len(b)}\r\n"
            f"Connection: {connection}\r\n\r\n").encode() + b


def start_server(port, certfile, keyfile, routes):
    """routes: path -> raw response bytes. Honors keep-alive: keeps reading
    more requests on the same TLS connection until the client disconnects
    -- a real server, not a close-after-one-request stand-in (this test's
    whole point is proving a connection SURVIVES being idle during a detour
    to another origin, which needs the far end to actually still be there)."""
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_3
    ctx.load_cert_chain(certfile=certfile, keyfile=keyfile)

    def handle(conn):
        try:
            tls = ctx.wrap_socket(conn, server_side=True)
        except (ssl.SSLError, OSError):
            conn.close(); return
        buf = b""
        try:
            while True:
                while b"\r\n\r\n" not in buf:
                    chunk = tls.recv(4096)
                    if not chunk:
                        return
                    buf += chunk
                head, _, buf = buf.partition(b"\r\n\r\n")
                path = head.split(b"\r\n")[0].split(b" ")[1].decode()
                tls.sendall(routes.get(path, canned("404 Not Found", "not found", "close")))
        except (ssl.SSLError, OSError):
            pass
        finally:
            try: tls.close()
            except OSError: pass

    raw = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    raw.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    for attempt in range(20):
        try:
            raw.bind(("0.0.0.0", port)); break
        except OSError:
            if attempt == 19: raise
            time.sleep(0.2)
    raw.listen(8)

    def loop():
        while True:
            try:
                conn, _ = raw.accept()
            except OSError:
                return
            threading.Thread(target=handle, args=(conn,), daemon=True).start()

    threading.Thread(target=loop, daemon=True).start()
    return raw


def run_qemu(serial_path, typed_cmd):
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash"}
        for ch in typed_cmd:
            s.sendall(("sendkey " + km.get(ch, ch) + "\n").encode()); time.sleep(0.12)
        # Two full TLS 1.3 handshakes (origins A and B) plus a PSK-capable
        # third leg all happen before this command's output settles -- more
        # crypto than any other single-command QEMU test in this suite, and
        # slow enough under emulation that the usual 25s budget occasionally
        # cuts the log off mid-run (confirmed by hand: identical run, longer
        # wait, completes cleanly). 45s gives real margin without slowing
        # the common case much.
        s.sendall(b"sendkey ret\n"); time.sleep(45)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-15x8-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    fails = 0
    srvA = srvB = None
    try:
        pem, key, der = gen_cert(work)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1

        routes_a = {
            "/starta": canned("302 Found", "go to B", "keep-alive", "https://10.0.2.2:8443/hop"),
            "/finish": canned("200 OK", "back on A, zero handshake", "close"),
        }
        routes_b = {
            "/hop": canned("302 Found", "go back to A", "close", "https://10.0.2.2/finish"),
        }
        srvA = start_server(443, pem, key, routes_a)
        srvB = start_server(8443, pem, key, routes_b)

        log = run_qemu(serial, "httpsget 10.0.2.2 /starta %d" % int(time.time()))

        checks = [
            ("redirect A -> B observed", "302 redirect -> https://10.0.2.2:8443/hop" in log),
            ("redirect B -> A observed", "302 redirect -> https://10.0.2.2/finish" in log),
            ("origin A: exactly one TCP connection (the very first)",
             log.count("TCP connected to 10.0.2.2:443") == 1),
            ("origin B: exactly one TCP connection", log.count("TCP connected to 10.0.2.2:8443") == 1),
            ("returning to A reused its still-open connection (zero handshake)",
             "reusing open connection to 10.0.2.2:443" in log),
            ("final response reached, status=200", "status=200" in log and "back on A, zero handshake" in log),
        ]
        for name, ok in checks:
            print(f"{name:60}: {'PASS' if ok else 'FAIL'}")
            if not ok: fails += 1
    finally:
        if srvA:
            try: srvA.close()
            except OSError: pass
        if srvB:
            try: srvB.close()
            except OSError: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n15.8 MULTI-ORIGIN SESSION CACHE (QEMU, real servers): " +
          ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
