#!/usr/bin/env python3
"""Phase 15.7 acceptance: TLS 1.3 session resumption, negotiated for real
inside QEMU against a genuine TLS 1.3 server (Python's `ssl` module, which
wraps OpenSSL -- the same engine real browsers resume against).

One QEMU boot, one httpsget process, two paths on the same origin:
`httpsget 10.0.2.2 /a /b <now_unix>`.

  - /a's response says "Connection: close": httpsget's own reuse policy
    (reusable(), Phase 15.4) then closes the connection itself, so /b forces
    a brand-new TCP + TLS handshake attempt -- exactly the "first connection,
    then a second one to the same origin" shape 15.7 exists for. This is the
    same technique tools/keepalive_qemu.py uses to force a reconnect.
  - The first connection is necessarily a full handshake (no ticket cached
    yet); while reading /a's response, the server's post-handshake
    NewSessionTicket arrives and httpsget caches it (tls_conn_take_ticket).
  - The second connection offers that cached ticket. If it works, this is a
    *resumed* handshake: no Certificate/CertificateVerify, straight to
    Finished.

Two independent witnesses confirm the server genuinely accepted the PSK
(not a silent fallback to a full handshake, RFC 8446 §4.1.4):
  1. Client-side trace: "PSK accepted -- resuming" / "Session resumed"
     appear only for the second connection, never the first.
  2. Server-side ground truth: Python's SSLSocket.session_reused, which
     wraps OpenSSL's SSL_session_reused() and is authoritative regardless of
     what the client claims -- verified locally beforehand to read True/False
     correctly for TLS 1.3 server-side sockets. Expected: [False, True].

Self-contained and reproducible: no private keys are committed; the
production user/ca_roots.h is restored on exit. Requires: qemu-system-i386,
openssl, the cross toolchain. Run from the repo root:
python3 tools/tls_resume_qemu.py
"""
import os, socket, ssl, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, cwd=ROOT, stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)


def gen_cert(work):
    key, pem, der = os.path.join(work, "leaf.key"), os.path.join(work, "leaf.pem"), os.path.join(work, "leaf.der")
    sh(f"openssl ecparam -name prime256v1 -genkey -noout -out {key}")
    sh(f'openssl req -x509 -new -key {key} -sha256 -days 10 -out {pem} '
       f'-subj "/CN=Aurora Resume Test" -addext "basicConstraints=critical,CA:FALSE" '
       f'-addext "keyUsage=critical,digitalSignature" -addext "subjectAltName=DNS:10.0.2.2"')
    sh(f"openssl x509 -in {pem} -outform DER -out {der}")
    return pem, key, der


def write_trust_header(path, root_der):
    b = open(root_der, "rb").read()
    out = ["/* GENERATED by tls_resume_qemu.py -- test root only, NOT committed. */", "#pragma once",
           "static const unsigned char ca_root_0[] = {", "    " + ",".join(str(x) for x in b), "};",
           "static const struct { const unsigned char *der; unsigned len; const char *name; } ca_roots[] = {",
           '    { ca_root_0, %d, "test root" },' % len(b), "};",
           "#define CA_ROOTS_N (sizeof ca_roots / sizeof ca_roots[0])"]
    open(path, "w").write("\n".join(out) + "\n")


def canned(body, connection):
    b = body.encode()
    return (f"HTTP/1.1 200 OK\r\nContent-Length: {len(b)}\r\nConnection: {connection}\r\n\r\n").encode() + b


def start_server(port, certfile, keyfile):
    """A real TLS 1.3 server (OpenSSL via Python's ssl module), issuing its
    own session tickets automatically -- nothing about ticket issuance or PSK
    acceptance is scripted or simulated. `reused` records, in connection
    order, what SSL_session_reused() reported for each accepted connection."""
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.minimum_version = ssl.TLSVersion.TLSv1_3
    ctx.load_cert_chain(certfile=certfile, keyfile=keyfile)

    reused = []
    routes = {
        "/a": canned("AAAA", "close"),
        "/b": canned("BBBB", "close"),
    }

    def handle(conn):
        try:
            tls = ctx.wrap_socket(conn, server_side=True)
        except (ssl.SSLError, OSError):
            conn.close(); return
        reused.append(bool(tls.session_reused))
        buf = b""
        try:
            while b"\r\n\r\n" not in buf:
                chunk = tls.recv(4096)
                if not chunk:
                    return
                buf += chunk
            head = buf.split(b"\r\n\r\n", 1)[0]
            path = head.split(b"\r\n")[0].split(b" ")[1].decode()
            tls.sendall(routes.get(path, canned("not found", "close")))
        except (ssl.SSLError, OSError):
            pass
        finally:
            try: tls.close()
            except OSError: pass

    raw = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    raw.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    for attempt in range(20):
        try:
            raw.bind(("0.0.0.0", port)); break
        except OSError:
            if attempt == 19: raise
            time.sleep(0.2)
    raw.listen(8)

    def loop():
        while True:
            try:
                conn, _ = raw.accept()
            except OSError:
                return
            threading.Thread(target=handle, args=(conn,), daemon=True).start()

    threading.Thread(target=loop, daemon=True).start()
    return raw, reused


def run_qemu(serial_path, typed_cmd):
    tmp = tempfile.mkdtemp(); mon = os.path.join(tmp, "m.sock")
    if os.path.exists(serial_path): os.remove(serial_path)
    q = ["qemu-system-i386", "-kernel", "aurora.elf", "-m", "64M",
         "-drive", "file=disk.img,format=raw,if=ide", "-display", "none",
         "-serial", "file:" + serial_path, "-monitor", "unix:%s,server,nowait" % mon,
         "-netdev", "user,id=n0", "-device", "virtio-net-pci,netdev=n0",
         "-no-reboot", "-no-shutdown"]
    p = subprocess.Popen(q, cwd=ROOT, stderr=subprocess.DEVNULL)
    try:
        s = None
        for _ in range(80):
            try:
                s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM); s.connect(mon); break
            except OSError: time.sleep(0.1)
        time.sleep(7)
        km = {" ": "spc", ".": "dot", "/": "slash"}
        for ch in typed_cmd:
            s.sendall(("sendkey " + km.get(ch, ch) + "\n").encode()); time.sleep(0.12)
        s.sendall(b"sendkey ret\n"); time.sleep(25)
        s.sendall(b"quit\n"); time.sleep(0.3); s.close()
    finally:
        p.terminate()
        try: p.wait(timeout=3)
        except subprocess.TimeoutExpired: p.kill()
    return open(serial_path, errors="replace").read() if os.path.exists(serial_path) else ""


def main():
    work = tempfile.mkdtemp(prefix="aurora-15x7-")
    prod = os.path.join(ROOT, "user/ca_roots.h")
    serial = os.path.join(work, "serial.log")
    fails = 0
    srv = None
    try:
        pem, key, der = gen_cert(work)
        write_trust_header(prod, der)
        if sh("make user/httpsget.elf disk.img").returncode != 0:
            print("build FAILED"); return 1

        srv, reused = start_server(443, pem, key)

        log = run_qemu(serial, "httpsget 10.0.2.2 /a /b %d" % int(time.time()))

        # Split into per-connection segments on "TCP connected to" (printed
        # exactly once per fetch_begin(), same convention as keepalive_qemu.py).
        segs = log.split("TCP connected to")
        conn_count = len(segs) - 1
        first, second = (segs[1], segs[2]) if conn_count >= 2 else ("", "")

        checks = [
            ("exactly two TCP connections", conn_count == 2),
            ("both requests got status=200", log.count("status=200") == 2),
            ("1st connection did a full handshake (no PSK offered)",
             "PSK offered" not in first and "PSK accepted" not in first),
            ("1st connection's NewSessionTicket was cached",
             "NewSessionTicket received" in first and "session ticket cached for 10.0.2.2:443" in first),
            ("2nd connection offered the cached ticket", "PSK offered" in second),
            ("2nd connection: server accepted the PSK (client trace)", "PSK accepted -- resuming" in second),
            ("2nd connection: no certificate exchanged (abbreviated path)",
             "Session resumed (PSK accepted)" in second and "Certificate depth=" not in second),
            ("server ground truth: [full, resumed] (SSL_session_reused)", reused == [False, True]),
        ]
        for name, ok in checks:
            print(f"{name:58}: {'PASS' if ok else 'FAIL'}")
            if not ok: fails += 1
    finally:
        if srv:
            try: srv.close()
            except OSError: pass
        subprocess.run(["git", "checkout", "--", "user/ca_roots.h"], cwd=ROOT,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        sh("make user/httpsget.elf disk.img")
        shutil.rmtree(work, ignore_errors=True)
    print("\n15.7 TLS SESSION RESUMPTION (QEMU, real server): " + ("ALL PASS" if fails == 0 else f"{fails} FAILURE(S)"))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
