/* tlsconnect: drive a real TLS 1.3 handshake over a real TCP socket and stop.
 *
 * The first time Aurora's TLS engine leaves the lab (trace-runner + synthetic
 * loopback) and runs over the live network. Deliberately narrow: connect, drive
 * the handshake to CONNECTED, print the milestone trace, exit. No HTTP, no GET,
 * no application data -- that is the next step (13.0b.3). Reaching CONNECTED here
 * proves TCP -> TLS 1.3 -> X.509 -> RSA-PSS all survive a real byte stream.
 *
 *   usage: tlsconnect [host-ip] [port]      (default 10.0.2.2 4433)
 *
 * The trust root is embedded (user/tls_test_root.h, generated by tools/der2c.py
 * from test/tls/cert.pem), so no filesystem is involved. The certificate is
 * checked against the name "aurora-test" (its SubjectAltName), while the TCP
 * connection is made to the given IP -- so run it against:
 *
 *   openssl s_server -accept 4433 -cert cert.pem -key key.pem -tls1_3
 *
 * on the host (reachable from the QEMU guest at 10.0.2.2). */
#include "libc.h"
#include "driver.h"     /* tls_driver_handshake, tls_transport */
#include "conn.h"
#include "x509.h"
#include "tls_test_root.h"

#define TLS_HOSTNAME "aurora-test"
/* Inside the test certificate's validity window (notBefore + 30 days). Aurora has
 * no wall clock; a real client would use one. Tied to test/tls/cert.pem. */
#define TLS_NOW 1784818880ULL

/* Big objects live in BSS, never on the 16 KiB user stack. */
static tls_conn          g_conn;
static tls_record_reader g_reader;
static x509_cert         g_root;
static uint8_t           g_scratch[2048];
static int               g_fd;

static int xport_read(void *ctx, uint8_t *buf, size_t cap)
{ (void)ctx; return read(g_fd, buf, (int)cap); }

static int xport_write(void *ctx, const uint8_t *buf, size_t len)
{ (void)ctx; return write(g_fd, buf, (int)len); }

static void trace_sink(void *ctx, tls_event ev, uint32_t detail)
{ (void)ctx; (void)detail; printf("[TLS] %s\n", tls_event_name(ev)); }

static int parse_port(const char *s, int dflt)
{
    int v = 0, any = 0;
    for (; *s >= '0' && *s <= '9'; s++) { v = v * 10 + (*s - '0'); any = 1; }
    return (any && v > 0 && v < 65536) ? v : dflt;
}

int main(int argc, char **argv)
{
    const char *host = (argc > 1) ? argv[1] : "10.0.2.2";
    int port = (argc > 2) ? parse_port(argv[2], 4433) : 4433;

    if (x509_parse(test_root_der, test_root_der_len, &g_root) != 0) {
        fprintf(2, "tlsconnect: embedded trust root failed to parse\n");
        return 1;
    }

    g_fd = inet_socket();
    if (g_fd < 0) { fprintf(2, "tlsconnect: no network (inet_socket failed)\n"); return 1; }

    printf("[tlsconnect] connecting to %s:%d (cert name \"%s\")\n", host, port, TLS_HOSTNAME);
    int rc = inet_connect(g_fd, host, port);
    if (rc == -2) { fprintf(2, "tlsconnect: DNS/host resolution failed\n"); close(g_fd); return 1; }
    if (rc != 0)  { fprintf(2, "tlsconnect: TCP connect failed (refused/timeout)\n"); close(g_fd); return 1; }
    printf("[tlsconnect] TCP connected, starting TLS handshake\n");

    /* Ephemeral key + client random. NOTE: NOT cryptographically secure -- a
     * placeholder seed for the first live bring-up; replace with real entropy
     * before any non-test use. */
    uint8_t priv[32], crand[32];
    unsigned seed = perf_us() ^ (unsigned)getpid();
    for (int i = 0; i < 32; i++) {
        seed = seed * 1103515245u + 12345u;
        priv[i]  = (uint8_t)(0x40 + i) ^ (uint8_t)(seed >> 16);
        crand[i] = (uint8_t)(0x80 + i) ^ (uint8_t)(seed >> 8);
    }

    tls_conn_init(&g_conn, TLS_HOSTNAME, priv, crand);
    tls_client_set_trust(&g_conn.fsm, &g_root, 1, TLS_NOW);
    tls_conn_set_trace(&g_conn, trace_sink, 0);
    tls_reader_init(&g_reader);

    tls_transport t = { xport_read, xport_write, 0 };
    int r = tls_driver_handshake(&g_conn, &g_reader, &t, g_scratch, sizeof g_scratch);

    if (r == TLS_DRIVE_OK) {
        printf("[tlsconnect] SUCCESS: TLS 1.3 handshake complete, CONNECTED\n");
    } else {
        const char *why;
        switch (r) {
        case TLS_DRIVE_EOF:       why = "peer closed before CONNECTED"; break;
        case TLS_DRIVE_READ_ERR:  why = "socket read error"; break;
        case TLS_DRIVE_WRITE_ERR: why = "socket write error"; break;
        case TLS_DRIVE_PROTOCOL:  why = "handshake rejected (see trace)"; break;
        case TLS_DRIVE_OVERFLOW:  why = "record stream buffer overflow"; break;
        case TLS_DRIVE_MALFORMED: why = "malformed record length"; break;
        default:                  why = "unknown"; break;
        }
        fprintf(2, "[tlsconnect] FAILED: %s (driver=%d, tls_error=%d)\n",
                why, r, (int)g_conn.fsm.error);
    }

    close(g_fd);
    return r == TLS_DRIVE_OK ? 0 : 1;
}
